<?php

/**
* Implementation of hook_context_default_contexts().
* 
*/
function saic_main_default_contexts() {
  $contexts = digitaria_utility_install_context_dir('saic_main');
  return $contexts;
}

/**
 * Implementation of hook_views_default_views().
 */
function saic_main_views_default_views() {
  return views_install_view_dir('saic_main');
}

/**
 * Implementation of hook_imagecache_default_presets
 */
function saic_main_imagecache_default_presets() {
  return digitaria_utility_install_imagecache('saic_main');
}

/**
* Implementation of hook_menu().
*/
function saic_main_menu() {
  $items = array();

  $items['admin/settings/404_settings'] = array(
    'title' => '404 page settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('saic_main_settings_form'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
  );

  $items['error/error_thanks'] = array(
    'title' => 'Thank you for reporting the problem.',
    'type' => MENU_CALLBACK,
    'access arguments' => array('access content'),
    'page callback' => 'error_thankyou'
  );

  $items['products/list'] = array(
    'title' => 'Products: Complete List',
    'type' => MENU_CALLBACK,
    'access arguments' => array('access content'),
    'page callback' => 'get_product_list'
  );

  $items['contractcenter/viewcon'] = array(
    'title' => 'Contract Center: View All Contracts',
    'type' => MENU_CALLBACK,
    'access arguments' => array('access content'),
    'page callback' => 'get_contract_list'
  );

  $items['search/custom'] = array(
    'page callback' => 'search_page',
    'access arguments' => array('search content'),
    'type' => MENU_CALLBACK,
  );

  $items['feature'] = array(
    'title' => 'Feature Stories',
    'type' => MENU_CALLBACK,
    'access arguments' => array('access content'),
    'page callback' => 'saic_featured_stories'
  );

  $items['tools/contact'] = array(
    'title' => 'Contact',
    'type' => MENU_CALLBACK,
    'access arguments' => array('access content'),
    'page callback' => 'get_contact_list'
  );

  $items['career/email-signup'] = array(
    'title' => 'Careers',
    'type' => MENU_CALLBACK,
    'access arguments' => array('access content'),
    'page callback' => 'get_email_form'
  );

  $items['search/advanced'] = array(
    'title' => 'Search',
    'type' => MENU_CALLBACK,
    'access arguments' => array('access content'),
    'page callback' => 'adv_search_page'
  );


  return $items;
}

/**
 * Implementation of hook_menu_alter().
 */
function saic_main_menu_alter(&$items) {
  // #39503: More restricted access for EE&I role.
  $items['admin/reports/status/run-cron']['access arguments'] = array('administer site configuration');
  $items['admin/settings/supercron']['access arguments'] = array('administer site configuration');
  $items['admin/settings/supercron/firewall']['access arguments'] = array('administer site configuration');
  $items['admin/settings/supercron/invocation']['access arguments'] = array('administer site configuration');
  $items['admin/settings/supercron/monitor']['access arguments'] = array('administer site configuration');
  $items['admin/content/node-settings/rebuild']['access arguments'] = array('administer site configuration');
}

function saic_main_settings_form() {
  $form = array();
  $form['error_page_content_404'] = array(
    '#type' => 'textarea',
    '#title' => t('Error Content'),
    '#default_value' => variable_get('error_page_content_404', ''),
  );
  return system_settings_form($form);
}

/**
 * Implementation of hook_block
 */
function saic_main_block($op = 'list', $delta = 0, $edit = array()) {
  switch ($op) {
    case 'list':
      $blocks['saic_stay_connected_frame'] = array(
        'info' => t("Stay Connected"),
      );
      $blocks['saic_block_title'] = array(
        'info' => t("Header title block"),
      );
      $blocks['saic_product_top'] = array(
        'info' => t("Product top"),
      );
      $blocks['saic_announcement_contact'] = array(
        'info' => t("Announcement Contact"),
      );
      $blocks['saic_stories_top'] = array(
        'info' => t("Stories top"),
      );
      $blocks['saic_stories_top_featured'] = array(
        'info' => t("Stories featured top"),
      );
      $blocks['resources_block'] = array(
        'info' => t("Resources block"),
      );
      $blocks['contacts_block'] = array(
        'info' => t("Contacts block"),
      );
      $blocks['saic_breadcrumbs'] = array(
        'info' => t("Breadcrumbs"),
      );
      $blocks['saic_job_search'] = array(
        'info' => t("Job Search block"),
      );
      $blocks['saic_latest_stories'] = array(
        'info' => t("Latest News"),
      );
      $blocks['saic_latest_news_rss'] = array(
        'info' => t("Latest News rss"),
      );
      $blocks['saic_latest_news_twitter'] = array(
        'info' => t("Latest News twitter - right"),
      );
      $blocks['saic_latest_news_twitter_center'] = array(
        'info' => t("Latest News twitter - center"),
      );
      $blocks['saic_eeandi_twitter'] = array(
        'info' => t("Latest EE&I News twitter - right"),
      );
      $blocks['saic_eeandi_twitter_center'] = array(
        'info' => t("Latest EE&I News twitter - center"),
      );
      $blocks['saic_latest_news_no_title'] = array(
        'info' => t("Latest News No Title"),
      );
      $blocks['saic_what_we_are_doing'] = array(
        'info' => t("What we're doing"),
      );
      $blocks['saic_facebook_find'] = array(
        'info' => t("Find Us On Facebook"),
      );
      $blocks['saic_share_page'] = array(
        'info' => t("Share This Page"),
      );
      $blocks['saic_share_footer'] = array(
        'info' => t("Share Footer"),
      );
      $blocks['saic_share_join_us'] = array(
        'info' => t("Join Us Footer"),
      );
      $blocks['saic_add_footer'] = array(
        'info' => t("Add this footer"),
      );
      $blocks['saic_latest_tweets'] = array(
        'info' => t("Twitter: Latest Tweets"),
      );
      $blocks['saic_view_solutions'] = array(
        'info' => t("View Solutions by"),
      );
      $blocks['saic_contact_us'] = array(
        'info' => t("Contact Us"),
      );
      $blocks['saic_feature_stories_header'] = array(
        'info' => t("Featured Stories Header"),
      );
      $blocks['saic_resources_download'] = array(
        'info' => t("Resources download block"),
      );
      $blocks['saic_resource_node_heading'] = array(
        'info' => t("Resources node heading"),
      );
      return $blocks;
      break;
    case 'view':
      switch ($delta) {
        case 'saic_product_top':
          $block['content'] = saic_product_top_block();
        break;
        case 'saic_stories_top':
          $block['content'] = saic_stories_top_block();
        break;
        case 'contacts_block':
          $block['content'] = saic_main_contacts_block();
          break;
        case 'resources_block':
          $block['content'] = saic_main_resources_block();
          break;
        case 'saic_view_solutions':
          $block['content'] = saic_view_solutions();
          break;
        case 'saic_add_footer':
          $block['content'] =theme('saic_add_footer');
          break;
        case 'saic_contact_us':
          $block['content'] =theme('saic_contact_us');
          break;
        case 'saic_job_search':
          $block['content'] =theme('saic_job_search');
          break;
        case 'saic_facebook_find':
          $block['content'] = theme('saic_facebook_find');
          break;
        case 'saic_share_page':
          $block['content'] = theme('saic_share_page');
          break;
        case 'saic_share_footer':
          $block['content'] = theme('saic_share_footer');
          break;
        case 'saic_stories_top_featured':
          $block['content'] = theme('saic_stories_top_featured');
          break;
        case 'saic_stay_connected_frame':
          $block['content'] = theme('saic_stay_connected_frame');
          break;
        case 'saic_share_join_us':
          $block['content'] = theme('saic_share_join_us');
          break;
        case 'saic_latest_tweets':
          $block['content'] = saic_latest_tweets();
          break;
        case 'saic_breadcrumbs':
          $block['content'] = theme('saic_breadcrumbs');
          break;
        case 'saic_latest_stories':
          $block['content'] = saic_latest_stories('Latest News');
          break;
        case 'saic_latest_news_no_title':
          $block['content'] = saic_latest_stories('Latest News',7,FALSE);
          break;
        case 'saic_what_we_are_doing':
          $block['content'] = saic_latest_stories("Read About What We're Doing", 16);
          break;
        case 'saic_resources_download':
           $block['content'] = block_saic_resources_download();
          break;
        case 'saic_resource_node_heading':
           $block['content'] = saic_resource_node_heading();
          break;
        case 'saic_latest_news_twitter':
           $block['content'] = saic_latest_news_twitter();
          break;
        case 'saic_latest_news_twitter_center':
           $block['content'] = saic_latest_news_twitter('center');
          break;
        case 'saic_eeandi_twitter':
           $block['content'] = saic_latest_news_twitter('right', 'SAICEngineering');
          break;
        case 'saic_eeandi_twitter_center':
           $block['content'] = saic_latest_news_twitter('center', 'SAICEngineering');
          break;
        case 'saic_announcement_contact':
          $block['content'] = saic_announcement_contact();
        break;
        case 'saic_block_title':
           $block['content'] = saic_block_title();
          break;
        case 'saic_latest_news_rss':
           $block['content'] = saic_latest_news_rss();
          break;
      }
      return $block;
      break;
  }
}

/**
 * Block 'View' callback for 'Rotator' block.
 */
function saic_main_block_rotator($nav_tag = NULL) {

  $block = array('subject' => '', 'content' => '');
  $nav_tag = taxonomy_get_term($nav_tag);
  if (!isset($nav_id)) {
    return $block;
  }

  $featured_rotator = '
  <div id="hero">
    <div class="slides">';
  
  $result = db_query("SELECT * FROM {content_type_rotator_image} WHERE type = 'rotator_image' and tid='%s' order by weight ASC", $nav_tag);
  if ($result) {
    $rows = array();
    while ($row = db_fetch_array($result)) {
      $rows[] = $row;
    }
    $row_count = 0;
    foreach ($rows as $row) {
      $featured_rotator .= '
        <a href="'.url($row['field_rotator_link']).'" title="'.$row['title'].'">'.$row['field_rotator_image'].'</a>';

      $row_count++;
    }
  }
  $featured_rotator .= '
    </div>
  </div>';

  // Get our new rotator object.
  $block['content'] = $featured_rotator;

  return $block;
}

function error_thankyou() {
  if($_GET['sid']) {
    include_once(drupal_get_path('module', 'webform') .'/includes/webform.submissions.inc');
    $submission = webform_get_submission('555',$_GET['sid']);
    if ( $submission->remote_addr != ip_address()  ) {
      drupal_not_found();
      module_invoke_all('exit');
      exit;
    }
    else {
      return theme('webform_contact_thankyou',$submission);
    }
  }
}

function saic_announcement_contact() {
  if ( arg(0) == 'node' && is_numeric(arg(1))) {
   $node_data = node_load(arg(1));
  
  $content =  $node_data->field_announcement_contact[0]['value'];

   return theme('saic_announcement_contact',$content);
  }
}

function saic_block_title() {
  if ( arg(0) == 'node' && is_numeric(arg(1))) {
   $node_data = node_load(arg(1));
   $title =  $node_data->title;
   return theme('saic_block_title',$title);
  }
}



/**
 * Implementation of hook_theme().
 */
function saic_main_theme() {
  return array(
    'saic_job_search' => array(
      'arguments' => array('nid' => NULL),
      'template' => 'job-search',
    ),
    'saic_error' => array(
      'template' => 'custom-error',
      'path' => base_path() . path_to_theme(),
      'arguments' => array(
        'code' => null,
        'title' => null,
        'description' => null,
        'messages' => null
      ),
    ),
    'adv_search_page' => array(
      'template' => 'page-search',
      'arguments' => array('content' => NULL),
    ),
    'saic_feature_stories' => array(
      'template' => 'page-saic_featured_stories',
      'arguments' => array('content' => NULL),
    ),
    'saic_block_title' => array(
      'template' => 'block-heading-title',
      'arguments' => array('title' => NULL),
    ),
    'saic_announcement_contact' => array(
      'template' => 'block-announcement-contact',
      'arguments' => array('content' => NULL),
    ),
    'saic_latest' => array(
      'arguments' => array('title' => NULL, 'data' => NULL, 'show_title' => NULL),
      'template' => 'latest-stories',
    ),
    'saic_view_solutions' => array(
      'template' => 'block-view-solutions',
      'arguments' => array('services' => NULL, 'markets' => NULL),
    ),
    'saic_resource_node_heading' => array(
      'arguments' => array('node' => NULL),
      'template' => 'block-resources-header',
    ),
    'saic_contact_us' => array(
      'template' => 'block-contact-us',
    ),
    'saic_facebook_find' => array(
      'template' => 'facebook-find-us',
    ),
    'saic_contacts_block_row' => array(
      'arguments' => array('content' => NULL),
      'template' => 'contacts-block-row',
    ),
    'saic_share_page' => array(
      'template' => 'share-this-page',
    ),
    'saic_stay_connected' => array(
      'template' => 'block-view-stay-connected',
    ),
    'saic_stories_top_featured' => array(
      'template' => 'block-stories-top-featured',
    ),
    'saic_resources_download' => array(
      'arguments' => array('download_link' => NULL),
      'template' => 'block-resources-download',
    ),
    'saic_breadcrumbs' => array(
      'template' => 'block-breadcrumb',
    ),
   'saic_stay_connected_frame' => array(
      'template' => 'block-stay_connected_frame',
    ),
    'saic_share_footer' => array(
      'template' => 'share-footer',
    ),
    'saic_block_contacts' => array(
      'arguments' => array('section' => NULL, 'content' => NULL),
      'template' => 'block-contacts',
    ),
    'saic_add_footer' => array(
      'template' => 'add-footer',
    ),
    'saic_stories_top' => array(
      'arguments' => array('node' => NULL),
      'template' => 'block-story-top',
    ),
    'saic_product_top' => array(
      'arguments' => array('node' => NULL),
      'template' => 'block-product-top',
    ),
    'saic_contact_list' => array(
      'template' => 'page-saic_contact_list',
      'arguments' => array('data' => NULL),
    ),
    'saic_product_list' => array(
      'template' => 'page-saic_product_list',
      'arguments' => array('keys' => NULL, 'used' => NULL, 'content' => NULL),
    ),
    'saic_contract_list' => array(
      'template' => 'page-saic_contract_list',
      'arguments' => array('keys' => NULL, 'used' => NULL, 'content' => NULL),
    ),
    'saic_product_list_section' => array(
      'template' => 'page-saic_product_list-section',
      'arguments' => array('key' => NULL, 'content' => NULL),
    ),
    'saic_contract_list_section' => array(
      'template' => 'page-saic_contract_list-section',
      'arguments' => array('key' => NULL, 'content' => NULL),
    ),
    'saic_featured_stories_row' => array(
      'template' => 'latest-stories-story-row',
      'arguments' => array('story' => NULL),
    ),
    'saic_content_podgroup_group_list_node_item' => array(
      'template' => 'content_podgroup-group_list_node_item',
      'arguments' => array(
        'title' => NULL,
        'link' => NULL,
        'link_class' => NULL,
        'show_date' => NULL,
        'more_link' => NULL,
        'date' => NULL,
  	'image_path' => NULL,
	'desc' => NULL,
        'display_type' => NULL,
      )),
    'saic_featured_stories_section' => array(
      'template' => 'latest-stories-story-section',
      'arguments' => array('taxonomy' => NULL, 'content' => NULL),
    ),
    'saic_product_list_section_row' => array(
      'template' => 'page-saic_product_list-section-row',
      'arguments' => array('data' => NULL),
    ),
    'webform_contact_thankyou' => array(
      'template' => 'webform_contact_thankyou',
      'arguments' => array('data' => NULL),
    ),
    'saic_contract_list_section_row' => array(
      'template' => 'page-saic_contract_list-section-row',
      'arguments' => array('data' => NULL),
    ),
    'saic_share_join_us' => array(
      'template' => 'share-this-page',
    ),
    'saic_latest_tweets' => array(
      'template' => 'latest-tweets',
      'arguments' => array('tweets' => NULL),
    ),
    'saic_latest_news_tweets' => array(
      'template' => 'block-latest-news-tweets',
      'arguments' => array('tweets' => NULL),
    ),
    'saic_latest_news_tweets_center' => array(
      'template' => 'block-latest-news-tweets-center',
      'arguments' => array('tweets' => NULL),
    ),
  );
}

function saic_main_map_content_type_fields($ref_node) {
  $mapped_fields = array();
  switch ($ref_node->type) {
    case 'person':
      $mapped_fields['nid'] = $ref_node->nid;
      $mapped_fields['date'] = NULL;
      $mapped_fields['link_class'] = NULL;
      $mapped_fields['title'] = $ref_node->title;
      $mapped_fields['link'] = $ref_node->path;
      $mapped_fields['desc'] = $ref_node->field_person_teaser[0]['value'];
      $mapped_fields['image_path'] = $ref_node->field_person_portrait[0]['filepath'];
      $mapped_fields['image_alt'] = $ref_node->field_person_portrait[0]['data']['alt'];
      $mapped_fields['link_text'] = $ref_node->title;
      break;

    case 'product':
      $mapped_fields['nid'] = $ref_node->nid;
      $mapped_fields['date'] = NULL;
      $mapped_fields['link_class'] = NULL;
      $mapped_fields['title'] = $ref_node->title;
      $mapped_fields['link'] = $ref_node->path;
      $mapped_fields['desc'] = $ref_node->field_product_teaser[0]['value'];
      $mapped_fields['image_path'] = $ref_node->field_product_image[0]['filepath'];
      $mapped_fields['image_alt'] = $ref_node->field_product_image[0]['data']['alt'];
      $mapped_fields['link_text'] = $ref_node->title;
      break;

    case 'resource':
      $mapped_fields['nid'] = $ref_node->nid;
      $mapped_fields['date'] = NULL;
      $mapped_fields['title'] = $ref_node->title;
      if(!empty($ref_node->field_resource_document_file[0]['filepath']))
      {
        $mapped_fields['link'] = $ref_node->field_resource_document_file[0]['filepath'];
        $mapped_fields['link_is_file'] = TRUE;
	      $mapped_fields['link_class'] = strpos($mapped_fields['link'], ".pdf") !== FALSE ? "pdf" : NULL;
      }
      else
      {
        $mapped_fields['link'] = $ref_node->path;
	      $mapped_fields['link_class'] = NULL;
      }
      $mapped_fields['desc'] = $ref_node->field_resource_teaser[0]['value'];
      $mapped_fields['image_path'] = $ref_node->field_resource_image[0]['filepath'];
      $mapped_fields['image_alt'] = $ref_node->field_resource_image[0]['data']['alt'];
      $mapped_fields['link_text'] = $ref_node->title;
      break;

    case 'service':
      $mapped_fields['nid'] = $ref_node->nid;
      $mapped_fields['date'] = NULL;
      $mapped_fields['link_class'] = NULL;
      $mapped_fields['title'] = $ref_node->title;
      $mapped_fields['link'] = $ref_node->path;
      $mapped_fields['desc'] = $ref_node->field_service_teaser[0]['value'];
      $mapped_fields['image_path'] = $ref_node->field_service_image[0]['filepath'];
      $mapped_fields['image_alt'] = $ref_node->field_service_image[0]['data']['alt'];
      $mapped_fields['link_text'] = $ref_node->title;
      break;

    case 'contract':
      $mapped_fields['nid'] = $ref_node->nid;
      $mapped_fields['date'] = NULL;
      $mapped_fields['link_class'] = NULL;
      $mapped_fields['title'] = $ref_node->title;
      $mapped_fields['link'] = $ref_node->path;
      $mapped_fields['desc'] = $ref_node->field_contract_teaser[0]['value'];
      $mapped_fields['image_path'] = $ref_node->field_contract_image[0]['filepath'];
      $mapped_fields['image_alt'] = $ref_node->field_contract_image[0]['data']['alt'];
      $mapped_fields['link_text'] = $ref_node->title;
      break;

    case 'announcement':
      $mapped_fields['nid'] = $ref_node->nid;
      $mapped_fields['date'] = strftime('%B %e %Y',strtotime($ref_node->field_announcement_date[0]['value']));
      $mapped_fields['link_class'] = NULL;
      $mapped_fields['title'] = $ref_node->title;
      $mapped_fields['link'] = $ref_node->path;
      $mapped_fields['desc'] = $ref_node->field_announcement_teaser[0]['value'];
      $mapped_fields['image_path'] = NULL;
      $mapped_fields['image_alt'] = NULL;
      $mapped_fields['link_text'] = $ref_node->title;
      break;

    case 'story':
      $mapped_fields['nid'] = $ref_node->nid;
      $mapped_fields['date'] = strftime('%B %e %Y',strtotime($ref_node->field_announcement_date[0]['value']));
      $mapped_fields['link_class'] = NULL;
      $mapped_fields['title'] = $ref_node->title;
      $mapped_fields['link'] = $ref_node->path;
      $mapped_fields['desc'] = $ref_node->field_story_teaser[0]['value'];
      $mapped_fields['image_path'] = $ref_node->field_story_image[0]['filepath'];
      $mapped_fields['image_alt'] = $ref_node->field_story_image[0]['data']['alt'];
      $mapped_fields['link_text'] = $ref_node->title;
      break;

    case 'press_release':
      $mapped_fields['nid'] = $ref_node->nid;
      $mapped_fields['date'] = strftime('%e %b %y',strtotime($ref_node->field_press_release_date[0]['value']));
      $mapped_fields['link_class'] = NULL;
      $mapped_fields['title'] = $ref_node->title;
      $mapped_fields['link'] = $ref_node->path;
      $mapped_fields['desc'] = $ref_node->field_press_release_teaser[0]['value'];
      $mapped_fields['image_path'] = NULL;
      $mapped_fields['image_alt'] = NULL;
      $mapped_fields['link_text'] = $ref_node->title;
      break;

    case 'in_the_news_article':
      $mapped_fields['nid'] = $ref_node->nid;
      if (!empty($ref_node->field_in_the_news_article_link[0]['url'])) {
        $mapped_fields['link'] = $ref_node->field_in_the_news_article_link[0]['url'];
        $mapped_fields['title'] = $ref_node->field_in_the_news_article_link[0]['title'];
        $mapped_fields['link_class'] = NULL;
      }
      $mapped_fields['date'] = strftime('%e %b %y',strtotime($ref_node->field_in_the_news_date[0]['value'])); 
      $mapped_fields['desc'] = $ref_node->field_in_the_news_teaser[0]['value'];
      $mapped_fields['image_path'] = NULL;
      $mapped_fields['image_alt'] = NULL;
      $mapped_fields['link_text'] = $ref_node->title;
      break;

    case 'audio':
      $mapped_fields['nid'] = $ref_node->nid;
      $mapped_fields['link'] = "partials/video/".$ref_node->nid;
      $mapped_fields['link_class'] = 'video_popup';
      $mapped_fields['title'] = $ref_node->title;
      $mapped_fields['date'] = date('d M Y',$ref_node->created);
      $mapped_fields['desc'] = $ref_node->field_audio_short_description[0]['value'];
      $mapped_fields['image_path'] = $ref_node->field_audio_thumbnail[0]['filepath'];
      $mapped_fields['image_alt'] = $ref_node->field_audio_thumbnail[0]['data']['alt'];
      $mapped_fields['link_text'] = $ref_node->title;
      break;

    case 'video':
      $mapped_fields['nid'] = $ref_node->nid;
      $mapped_fields['link'] = "partials/video/".$ref_node->nid;
      $mapped_fields['link_class'] = 'video_popup';
      $mapped_fields['title'] = $ref_node->title;
      $mapped_fields['date'] = date('d M Y',$ref_node->created);
      $mapped_fields['desc'] = $ref_node->field_video_short_description[0]['value'];
      $mapped_fields['image_path'] = $ref_node->field_video_thumbnail[0]['filepath'];
      $mapped_fields['image_alt'] = $ref_node->field_video_thumbnail[0]['data']['alt'];
      $mapped_fields['link_text'] = $ref_node->title;
      break;

    case 'gallery':
      $mapped_fields['nid'] = $ref_node->nid;
      $mapped_fields['link'] = "partials/video/".$ref_node->nid;
      $mapped_fields['link_class'] = 'video_popup';
      $mapped_fields['title'] = $ref_node->title;
      $mapped_fields['date'] = date('d M Y',$ref_node->created);
      $mapped_fields['image_path'] = NULL;
      $mapped_fields['image_alt'] = NULL;
      $mapped_fields['link_text'] = $ref_node->title;
      break;

    case 'ddp_image':
      $mapped_fields['nid'] = $ref_node->nid;
      $mapped_fields['link'] = "partials/video/".$ref_node->nid;
      $mapped_fields['link_class'] = 'video_popup';
      $mapped_fields['title'] = $ref_node->title;
      $mapped_fields['date'] = date('d M Y',$ref_node->created);
      $mapped_fields['desc'] = $ref_node->field_image_short_desc[0]['value'];
      $mapped_fields['image_path'] = $ref_node->field_image_thumbnail[0]['filepath'];
      $mapped_fields['image_alt'] = $ref_node->field_image_thumbnail[0]['data']['alt'];
      $mapped_fields['link_text'] = $ref_node->title;
      break;

    default:
      $mapped_fields['nid'] = $ref_node->nid;
      $mapped_fields['title'] = $ref_node->title;
      $mapped_fields['link'] = $ref_node->path;
      $mapped_fields['link_class'] = NULL;
      $mapped_fields['date'] = NULL;
      $mapped_fields['desc'] = NULL;
      $mapped_fields['image_path'] = NULL;
      $mapped_fields['image_alt'] = NULL;
      $mapped_fields['link_text'] = $ref_node->title;
      break;
  }  

  return $mapped_fields;
}

function get_email_form() {
  echo theme('saic_stay_connected');
  exit;
}

function get_contact_list() {
  return theme('saic_contact_list');
}

function get_contract_list() {
  $products = saic_get_contract_list();
  $list_content = NULL;
  // Build the List Section Content
  foreach ($products as $key => $row) {
    $key_content = NULL;
        
    // echo 'Row'; print_r($row);
    // Build the List Section Row Content
    foreach ($row as $r) {
      $key_content .= theme('saic_contract_list_section_row', $r);
    }
    $content .= theme('saic_contract_list_section', $key, $key_content);
  }
  // Return the List Content
  $selected_products = array_keys($products);
  $allowed_keys = array('#', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z');
  return theme('saic_contract_list', $allowed_keys, $selected_products, $content);
}

function get_product_list() {
  $products = saic_get_product_list();
  $list_content = NULL;
  // Build the List Section Content
  foreach ($products as $key => $row) {
    $key_content = NULL;
    // Build the List Section Row Content
    foreach ($row as $r) {
      $key_content .= theme('saic_product_list_section_row', $row);
    }
    $content .= theme('saic_product_list_section', $key, $key_content);
  }
  // Return the List Content
  $selected_products = array_keys($products);
  $allowed_keys = array('#', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z');
  return theme('saic_product_list', $allowed_keys, $selected_products, $content);
}

function saic_stories_top_block() {
  if ( arg(0) == 'node' && is_numeric(arg(1))) {
    $node_data = node_load(arg(1));
  }
  return theme('saic_stories_top',$node_data);
}

function saic_product_top_block() {
  if ( arg(0) == 'node' && is_numeric(arg(1))) {
    $node_data = node_load(arg(1));
  }
  return theme('saic_product_top',$node_data);
}

function saic_check_left_menu($node) {
  if ($node->type == 'magazine'
    || $node->type == 'magazine_article'
    || $node->type == 'magazine_issue'
    || $node->type == 'webform'
    || arg(0) =='customerror'
    || arg(1) =='registerthankyou'
    || (arg(0) =='tools' && arg(1) =='contact')
    || (arg(0) =='news' && arg(1) =='resources')) {
    return TRUE;
  }
  if (!isset($node->field_page_left_menu[0]['value'])) {
    return FALSE;
  }
  elseif ($node->field_page_left_menu[0]['value'] == 1 && !empty($node->field_pod_ft_i_b_sn_move_nav[0]['value'])) {
    return TRUE;
  }
  elseif ($node->field_page_left_menu[0]['value'] == 0) {
    return FALSE;
  }
  elseif ($node->field_pod_ft_i_b_sn_move_nav[0]['value'] == 1) {
    return FALSE;
  }
  else {
    return TRUE;
  }
}

function saic_check_breadcrumb($node) {
  if ($node->type == 'magazsaic_latest_news_tweetsine'
          || $node->type == 'magazine_article'
          || $node->type == 'magazine_issue'
          || arg(0) =='customerror'
          || arg(1) =='registerthankyou'
          || (arg(0) =='tools' && arg(1) =='contact')
          || (arg(0) =='news' && arg(1) =='resources')) {
    return TRUE;
  }
  if ($node->field_pod_ft_i_b_sn_move_nav[0]['value'] == 1) {
    return FALSE;
  }
  if (empty($node->field_page_breadcrumb[0]['value'])) {
    return FALSE;
  } 
  elseif ($node->field_page_breadcrumb[0]['value'] == 0) {
    return FALSE;
  }
  else {
    return TRUE;
  }
}

function saic_check_breadcrumb_page() {
  if(arg(0) =='error' || arg(0) =='customerror' || arg(1) =='registerthankyou'|| (arg(0) =='tools' && arg(1) =='contact') || (arg(0) =='news' && arg(1) =='resources') || (arg(0) =='contractcenter' && arg(1) =='viewcon')){
    return TRUE;
  }
  else {
    return FALSE;
  }
}

function saic_main_load_block_from_id($block_id) {
  $result = db_query("SELECT bid, module, delta FROM {blocks} WHERE bid = %d", $block_id);
  $block_data = db_fetch_object($result);
  $block = module_invoke($block_data->module, 'block', 'view', $block_data->delta);
  return $block['content'];
}

function saic_main_load_block_from_delta($block_delta) {
  $result = db_query("SELECT bid, module, delta FROM {blocks} WHERE delta = '%s' and theme = 'saic' ", $block_delta);
  $block_data = db_fetch_object($result);
  $block = module_invoke($block_data->module, 'block', 'view', $block_data->delta);
  return $block['content'];
}

function saic_main_get_blocks() {
  $avail_blocks = array();
  $result = db_query("SELECT bid, module, delta FROM {blocks} where module IN ('saic_main', 'block', 'webform', 'saic_project','saic_news_archive') group by delta");

  $allowed_blocks = array('saic_stay_connected_frame','saic_latest_tweets','saic_what_we_are_doing', 'saic_latest_news_no_title', 'saic_latest_news_rss','saic_latest_stories', 'saic_view_solutions', 'saic_stay_connected_frame', 'saic_facebook_find', 'saic_share_page', 'saic_job_search','saic_latest_news_twitter_center','saic_latest_news_twitter','saic_eeandi_twitter_center','saic_eeandi_twitter');

  while ($block = db_fetch_object($result)) {
    if ($block->module != 'saic_main' || in_array($block->delta, $allowed_blocks)) {
      $block_info = module_invoke($block->module, 'block', 'list');
      if ($block_info[$block->delta]['info']) {
        // uppercasing block info to be sorted
        $avail_blocks[$block->bid] = ucfirst($block_info[$block->delta]['info']);
      }
    }
  }
  // sorted alpabethically for easier lookup
  asort($avail_blocks);  
  return $avail_blocks;
}

function saic_main_get_primary_menu_links() {
  $avail_menus = array();
  $result = db_query("SELECT link_title,mlid,menu_name FROM {menu_links} where hidden = 0 and depth = 1 and menu_name = 'primary-links' order by weight limit 5");
  while ($menus = db_fetch_object($result)) {
    $avail_menus[$menus->mlid] = $menus->link_title;
  }
  return $avail_menus;
}


function search_page() {
  return menu_execute_active_handler('search/apachesolr_search/'. search_get_keys());
}


/**
 * Implementation of hook_form_alter().
 */
function saic_main_form_alter(&$form, &$form_state, $form_id) {
  if($form_id == 'search_form') {
    $form['#access']  = FALSE;
  }
  if($form_id == 'search_block_form') {
    $form['#action'] = '/search/custom/';
  }

  if(isset($form['options']['promote'])) {
    unset($form['options']['promote']);
  }
  if(isset($form['options']['sticky'])) {
    unset($form['options']['sticky']);
  }

  if ($form_state['webform']) {
    $form['actions']['submit']['#prefix'] ="<div style='border-bottom:1px solid #D4D4D4; padding-bottom:20px; height: 1px;'></div><div class=\"center\"><div class='submitBtn'>";
    $form['actions']['submit']['#theme'] = 'button';
    $form['actions']['submit']['#button_type'] = 'button';
    // $form['actions']['submit']['#attributes'] = array(
    //   'src' => '/sites/all/themes/saic/images/new/btn_right.gif'
    // );
    $form['actions']['submit']['#suffix'] = '</div></div>';
  }


}

function saic_resource_node_heading() {
 if ( arg(0) == 'node' && is_numeric(arg(1))) {
    $node_data = node_load(arg(1));
    return theme('saic_resource_node_heading', $node_data);
 }
}

function block_saic_resources_download() {

  global $base_path;
  if(!isset($_COOKIE['download_access'])) { 
      $download_link = $base_path .'news/resourcesRegister?docid='.arg(1);
  }
  else if ( arg(0) == 'node' && is_numeric(arg(1))) {
    $node_data = node_load(arg(1));
    $download_link = $base_path . $node_data->field_resource_document_file[0]['filepath'];
  }

  return theme('saic_resources_download', $download_link);
}

/**
 *
 */
function saic_view_solutions() {

  $get_services = "
    SELECT           
     node.title,
     node.nid      
    FROM 
      node      
    WHERE        
      node.status <> 0      
    AND        
      node.type = 'service'      
    GROUP BY 
      node.vid     
   ";

   $data = array();
   $result = db_query($get_services);
   while ($row = db_fetch_array($result)) {
    $row['path'] = drupal_get_path_alias( 'node/' . $row['nid']);
    $services[] = $row;
   }

  $get_markets = "
    SELECT           
     node.nid,
     field_market_link_url,
     field_market_link_title as title
    FROM 
      node,
      content_type_market      
    WHERE        
      node.status <> 0      
    AND        
      node.type = 'market'     
    AND
       content_type_market.vid = node.vid
    GROUP BY 
      node.vid     
   ";

   $markets = array();
   $result = db_query($get_markets);
   while ($mrow = db_fetch_array($result)) {
    $mrow['path'] = $mrow['field_market_link_url'];
    $markets[] = $mrow;
   }

  return theme('saic_view_solutions', $services, $markets);
}

function saic_get_contract_list() {
  $get_products = "
  SELECT            
     node.title, 
     node.nid
  FROM 
    node node       
  WHERE        
    node.status <> 0      
  AND        
    node.type = 'contract'      
  GROUP BY 
    node.nid    
  ORDER BY 
    node.title
  ";

  $data = array();
  $result = db_query($get_products);
  while ($row = db_fetch_array($result)) {
    $key = strtoupper(substr($row['title'], 0, 1));
    if (preg_match('/^[A-Z]$/', $key)) {
      $array_key = $key;
    }
    else {
      $array_key = '#';
    }
    $node = (array)node_load($row['nid']);
    $data[$array_key][] = $node;
  }

  return $data;
}

function saic_get_product_list() {
  $get_products = "
  SELECT    
     field_product_sub_title_value,        
     node.title, 
     node.nid
  FROM 
    node node       
  LEFT JOIN content_type_product ON node.vid = content_type_product.vid     
  WHERE        
    node.status <> 0      
  AND        
    node.type = 'product'      
  GROUP BY 
    node.vid     
  ORDER BY 
    node.title
  ";

  $data = array();
  $result = db_query($get_products);
  while ($row = db_fetch_array($result)) {
    $row['path'] = drupal_get_path_alias( 'node/' . $row['nid']);
    $key = strtoupper(substr($row['title'], 0, 1));
    if (preg_match('/^[A-Z]$/', $key)) {
      $array_key = $key;
    }
    else {
      $array_key = '#';
    }
    $data[$array_key][] = $row;
  }

  return $data;
}

function saic_main_resources_block() {
  $get_stories = "SELECT     
     f.filepath,  
     story.field_story_date_value,       
     node.title,    
     field_story_teaser_value as teaser,  
     node.vid,
     term_node.tid,
     story.nid  as nid
  FROM node node       
  LEFT JOIN content_type_story story ON node.vid = story.vid
  LEFT JOIN term_node ON term_node.vid = story.vid     
  LEFT JOIN node_revisions nv ON node.vid = nv.vid  
  LEFT JOIN files f ON story.field_story_image_fid = f.fid
  WHERE        
    node.status <> 0      
  AND        
    node.type = 'story'      
  GROUP BY 
    node.vid     
  ORDER BY 
    story.field_story_date_value DESC
  ";

   $data = array();
   $result = db_query($get_stories);
   while ($row = db_fetch_array($result)) {
    $row['path'] = drupal_get_path_alias( 'node/' . $row['nid']);
    $row['filepath'] =  digitaria_imagecache_apply_preset("featured_stories_thumb",  $row['filepath']);
    $data[$row['tid']][] = $row;
   }

  $list_content = NULL;
  $key_content = NULL;

  foreach ($data as $key) {
    $taxonomy = taxonomy_get_term( $key[0]['tid']);
    foreach ($key as $story) {
      $key_content .= theme('saic_featured_stories_row', $story);
    }
    $content .= theme('saic_featured_stories_section', $taxonomy, $key_content);
  }

  return theme('saic_feature_stories', $content);
}

function saic_main_contacts_block() {

  $get_stories = "SELECT      
     node.title,    
     node.vid,
     field_contract_prim_link_value,
     field_contact_primary_info_value,
     field_contract_secondary_link_value,
     field_ontract_secondary_info_value,
     term_node.tid,
     contact.nid  as nid
  FROM node node       
  LEFT JOIN content_type_contact contact ON node.vid = contact.vid
  LEFT JOIN term_node ON term_node.vid = contact.vid     
  WHERE        
    node.status <> 0      
  AND        
    node.type = 'contact'      
  GROUP BY 
    node.vid     
  ";

   $data = array();
   $result = db_query($get_stories);
   while ($row = db_fetch_array($result)) {
    $data[$row['tid']][] = $row;
   }

  $list_content = NULL;
  $key_content = NULL;
  foreach ($data as $key) {
    $key_content = '';
    $taxonomy = taxonomy_get_term( $key[0]['tid']);
    foreach ($key as $contact) {
      $key_content .= theme('saic_contacts_block_row', $contact);
    }
    $content .= theme('saic_block_contacts', $taxonomy, $key_content);
  }

  return $content;
}

function saic_featured_stories() {
  $get_stories = "SELECT     
     f.filepath,  
     story.field_story_date_value,       
     node.title,    
     field_story_teaser_value as teaser,  
     node.vid,
     term_node.tid,
     story.nid  as nid
  FROM node node       
  LEFT JOIN content_type_story story ON node.vid = story.vid
  LEFT JOIN term_node ON term_node.vid = story.vid     
  LEFT JOIN term_data ON term_data.tid = term_node.tid  
  LEFT JOIN node_revisions nv ON node.vid = nv.vid  
  LEFT JOIN files f ON story.field_story_image_fid = f.fid
  WHERE        
    node.status <> 0      
  AND        
    node.type = 'story'      
  AND
    term_data.vid = 4
  GROUP BY 
    node.nid     
  ORDER BY 
    term_data.weight DESC
  ";

   $data = array();
   $result = db_query($get_stories);
   while ($row = db_fetch_array($result)) {
    $row['path'] = drupal_get_path_alias( 'node/' . $row['nid']);
    $row['filepath'] =  digitaria_imagecache_apply_preset("featured_stories_thumb",  $row['filepath']);
    $data[$row['tid']][] = $row;
   }

  $list_content = NULL;
  $key_content = NULL;

  foreach ($data as $key) {
    $key_content = '';
    $taxonomy = taxonomy_get_term( $key[0]['tid']);
    foreach ($key as $story) {
      $key_content .= theme('saic_featured_stories_row', $story);
    }
    $content .= theme('saic_featured_stories_section', $taxonomy, $key_content);
  }

  return theme('saic_feature_stories', $content);
}

function saic_main_filter($op, $delta = 0, $format = -1, $text = '') {

  if ($op == 'list') {
    return array(
      0 => t('Substitute superscript trademark for [trademark] tag'),
    );
  }
  $content = $text;
  switch ($delta) {
    case 0:
      $content = saic_main_trademark_filter($op, $text);
      break;
  }

  return $content;
}    

function saic_main_trademark_filter($op, $text){
  switch ($op) {
    case 'description':
      $content = t('Substitute superscript trademark for [trademark] tag');
      break;
    case 'prepare':
      $content = $text;
      break;
    case 'process':
      if (preg_match('/\[trademark\]/', $text, $matches)) {
        $trademark = '&trade;';
        $content = preg_replace('/\[trademark\]/', $trademark, $text);
      } else {
        $content = $text;
      }
      break;
    case 'settings':
      $content = $form;
      break;
      }
  return $content;
}

function saic_latest_stories($page_title, $limit = 7,$show_title = TRUE) {

  $get_stories = "SELECT       
     story.field_story_date_value,       
     node.title,       
     story.nid  as nid
  FROM node node       
  LEFT JOIN content_type_story story ON node.vid = story.vid     
  WHERE        
    node.status <> 0      
  AND        
    node.type = 'story'      
  GROUP BY 
    node.vid     
  ORDER BY 
    story.field_story_date_value DESC
  LIMIT 
    0, ". $limit ."
  ";

   $data = array();
   $result = db_query($get_stories);
   while ($row = db_fetch_array($result)) {
    $row['path'] = drupal_get_path_alias( 'node/' . $row['nid']);
    $row['date'] = date("d M Y", strtotime($row['field_story_date_value']));
    $data[] = $row;
   }

  return theme('saic_latest', $page_title, $data,$show_title);
}


function saic_latest_news_rss() {
  $ch = curl_init("http://investors.saic.com/corporate.rss?c=193857&Rule=Cat=news~subcat=ALL");
  curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
  curl_setopt($ch, CURLOPT_HEADER, 0);
  $data = curl_exec($ch);
  curl_close($ch);
  $xml = simplexml_load_string($data); 
  $news_items = simpleXMLToArray($xml);
  $news_items['channel']['item']  = array_slice ($news_items['channel']['item'], 0,6);

  $data = array();
  foreach($news_items['channel']['item'] as $index => $item) {
    $row['path'] = $item['link'];
    $row['date'] = date("d M Y", strtotime($item['pubDate']));
    $row['title'] = truncate_utf8($item['title'],91,FALSE,TRUE);
    $data[] = $row;
  }

  return theme('saic_latest', $page_title, $data,FALSE);
}

    function simpleXMLToArray($xml,
                    $flattenValues=true,
                    $flattenAttributes = true,
                    $flattenChildren=true,
                    $valueKey='@value',
                    $attributesKey='@attributes',
                    $childrenKey='@children'){

        $return = array();
        if(!($xml instanceof SimpleXMLElement)){return $return;}
        $name = $xml->getName();
        $_value = trim((string)$xml);
        if(strlen($_value)==0){$_value = null;};

        if($_value!==null){
            if(!$flattenValues){$return[$valueKey] = $_value;}
            else{$return = $_value;}
        }

        $children = array();
        $first = true;
        foreach($xml->children() as $elementName => $child){
            $value = simpleXMLToArray($child, $flattenValues, $flattenAttributes, $flattenChildren, $valueKey, $attributesKey, $childrenKey);
            if(isset($children[$elementName])){
                if($first){
                    $temp = $children[$elementName];
                    unset($children[$elementName]);
                    $children[$elementName][] = $temp;
                    $first=false;
                }
                $children[$elementName][] = $value;
            }
            else{
                $children[$elementName] = $value;
            }
        }
        if(count($children)>0){
            if(!$flattenChildren){$return[$childrenKey] = $children;}
            else{$return = array_merge($return,$children);}
        }

        $attributes = array();
        foreach($xml->attributes() as $name=>$value){
            $attributes[$name] = trim($value);
        }
        if(count($attributes)>0){
            if(!$flattenAttributes){$return[$attributesKey] = $attributes;}
            else{
              if(is_array($return) && is_array($attributes) ) {
                $return = array_merge($return, $attributes);
              }
            }
        }
       
        return $return;
    }

function saic_latest_news_twitter($position = 'right', $feed = 'SAICinc') {

  if ($position == 'right') {
    $limit =  6;
  }
  else {
    $limit =  10;
  }

  // Get the node ID for the tweet_feed of SAICinc
  $get_feed_id = "
  SELECT       
      node.nid as nid
  FROM 
    node node,      
    content_type_twitter_feed tweet_feed
  WHERE        
    node.status <> 0   
  AND        
    node.type = 'twitter_feed'
  AND
    field_twitter_feed_alias_value = '%s'
  AND
    node.vid = tweet_feed.vid
  ";
  
  $result = db_query($get_feed_id, $feed);
  $feed_id= db_fetch_array($result);

  $get_tweets = "
    SELECT       
     node.nid
    FROM 
      node node,       
      content_type_tweet tweet
    WHERE        
      node.status <> 0  
    AND        
      node.type = 'tweet'
    AND
      field_tweet_source_nid  = '". $feed_id['nid'] ."'
    AND
       node.vid = tweet.vid 
    GROUP BY 
      node.vid
    ORDER BY
      node.created DESC
    LIMIT 
      0, ". $limit;

   $data = array();
   $result = db_query($get_tweets);
   while ($row = db_fetch_array($result)) {
    $node = node_load($row['nid']);
    $date = $node->field_tweet_published_date[0]['value'];
    $guid = $node->field_tweet_guid[0]['value'];
    $days = floor((time() - strtotime($date))/86400);
    $row['days_since'] =  date('F d Y', strtotime($date)); 

    $link =  $row['days_since'];
    $row['body'] = theme_digi_twitter_tweet_body($node->body);
    $twitter_link = theme_digi_twitter_tweet_body_link($node->body);
    $row['body'] = $twitter_link['body'];
    $row['link'] = $twitter_link['link'];
    $data[] = $row;
   }
  if($position == 'right') {
    return theme('saic_latest_news_tweets',$data);
  }
  else {
    return theme('saic_latest_news_tweets_center',$data);
  }
}

function saic_latest_tweets($tweet_alias = 'SAICinc', $limit = 5) {

  // Get the node ID for the tweet_feed of SAICinc
  $get_feed_id = "
  SELECT       
      node.nid as nid
  FROM 
    node node,      
    content_type_twitter_feed tweet_feed
  WHERE        
    node.status <> 0   
  AND        
    node.type = 'twitter_feed'
  AND
    field_twitter_feed_alias_value = 'SAICinc'
  AND
    node.vid = tweet_feed.vid
  ";
  
  $result = db_query($get_feed_id);
  $feed_id= db_fetch_array($result);

  $get_tweets = "
    SELECT       
     node.nid
    FROM 
      node node,       
      content_type_tweet tweet
    WHERE        
      node.status <> 0  
    AND        
      node.type = 'tweet'
    AND
      field_tweet_source_nid  = '". $feed_id['nid'] ."'
    AND
       node.vid = tweet.vid 
    GROUP BY 
      node.vid
    ORDER BY
      node.created DESC
    LIMIT 
      0, ". $limit;

   $data = array();
   $result = db_query($get_tweets);
   while ($row = db_fetch_array($result)) {
    $node = node_load($row['nid']);
    $date = $node->field_tweet_published_date[0]['value'];
    $guid = $node->field_tweet_guid[0]['value'];
    $days = floor((time() - strtotime($date))/86400);
    if ($days) {
      $row['days_since'] = $days . ' days ago';
    }
    else
       $row['days_since'] = 'today';

    $link =  l($row['days_since'], $guid );
    $row['body'] = theme_digi_twitter_tweet_body($node->body) . ' ' . $link;
    $data[] = $row;
   }

  return theme('saic_latest_tweets', $data);
}

/**
 * Implementation of hook_content_type_tag_types
 */
function saic_main_content_type_tag_types($element) {
  $content_types = NULL;
  if ($element['#field_name'] == 'field_list_group_tags') {
    $content_types = array(
      'audio' => 'Audio',
      'story' => 'Story',
      'in_the_news_article' => 'In the News',
      'announcement' => 'Announcement',
      'contract' => 'Contract',
      'ddp_image' => 'Image',
      'person' => 'Person',
      'page' => 'Page',
      'press_release' => 'Press Release',
      'product' => 'Product',
      'service' => 'Service',
      'story' => 'Story',
      'video' => 'Video'
    );
  }
  return $content_types;
}

function saic_main_check_valid_resource_id($resource_id) {
  $get_resource = "
    SELECT       
     node.nid
    FROM 
      node node
    WHERE        
      node.status <> 0  
    AND        
      node.type = 'resource'
    AND
      node.nid = $resource_id";

  $result = db_query($get_resource);
  $row = db_fetch_array($result);

  if (empty($row))
    return FALSE;
  else
    return TRUE;
}

function _saic_main_webform_component_mapping($node) {
  $mapping = array();
  $components = $node->webform['components'];
  foreach ($components as $i => $component) {
    $key = $component['form_key'];
    $mapping[$key] = $i;
  }
  return $mapping;
}

function check_media_page() {
  if ('media' == arg(0))
     return TRUE;
  if ('node' == arg(0) && preg_match('/[0-9]+/', arg(1))) {
    $node = node_load(arg(1));
    if ($node->type == 'video' || $node->type == 'audio' || $node->type == 'ddp_image') {
      return TRUE;
    }
    else {
      return FALSE;
    }
  }
  else {
    return FALSE;
  }
}


function saic_main_perm() {
  $permissions = array(
    'access content editor',
  );
  return $permissions;
}

/**
 * Implementation of hook_access().
 */
function saic_main_node_access($op, $node, $account = null){
  if($node->type == 'tweet' && user_access('access content editor')) {
    return 0;
  }
}


function saic_main_access_tweet() {
  return !user_access('access content editor');
}




function saic_main_apachesolr_prepare_query(&$query, &$params, $caller) {

  // TODO: http://www.saic.com/search/ 
  // OR sub query, + - and "" supported
 // per page, date, file type, keywords appear logic

  $query->set_available_sort('changed', array(
       'title' => t('changed'),
       'default' => 'desc', // or 'desc'
      ));


  //$subquery = apachesolr_drupal_query();
  //$subquery->add_filter('type', 'node_type_one');
  //$subquery->add_filter('type', 'node_type_two');
  //$query->add_subquery($subquery, 'OR');

  //if(FILETYPE) {
    // PDF XLS PPT DOC
   //$subquery->add_filter('type', 'resource');
  //}

  // If no sort is selected, set the default sort.
  if ($_GET['solrsort'] == 'changed') {
    $query->set_solrsort('changed', 'desc');
  }
  else {
    $query->set_solrsort('score', 'desc');
  }
  //print_r($params);
}


function adv_search_page() {
  return theme('adv_search_page');
}



