<?php

/**
 * Implementation of hook_menu_default_menu_links().
 */
function microsite_menus_menu_default_menu_links() {
  $menu_links = array();

  // Exported menu link: primary-links:node/1555
  $menu_links['primary-links:node/1555'] = array(
    'menu_name' => 'primary-links',
    'link_path' => 'node/1555',
    'router_path' => 'node/%',
    'link_title' => 'Food Protection Solutions',
    'options' => array(
      'attributes' => array(),
    ),
    'module' => 'menu',
    'hidden' => '0',
    'external' => '0',
    'has_children' => '0',
    'expanded' => '0',
    'weight' => '-44',
    'parent_path' => 'node/1558',
  );
  // Exported menu link: primary-links:node/1558
  $menu_links['primary-links:node/1558'] = array(
    'menu_name' => 'primary-links',
    'link_path' => 'node/1558',
    'router_path' => 'node/%',
    'link_title' => 'Infrastructure',
    'options' => array(
      'attributes' => array(),
    ),
    'module' => 'menu',
    'hidden' => '0',
    'external' => '0',
    'has_children' => '1',
    'expanded' => '1',
    'weight' => '-40',
    'parent_path' => 'node/311',
  );
  // Exported menu link: primary-links:node/1559
  $menu_links['primary-links:node/1559'] = array(
    'menu_name' => 'primary-links',
    'link_path' => 'node/1559',
    'router_path' => 'node/%',
    'link_title' => 'Audio/Video, Visualization and Wireless',
    'options' => array(
      'attributes' => array(),
    ),
    'module' => 'menu',
    'hidden' => '0',
    'external' => '0',
    'has_children' => '0',
    'expanded' => '0',
    'weight' => '-50',
    'parent_path' => 'node/1574',
  );
  // Exported menu link: primary-links:node/1560
  $menu_links['primary-links:node/1560'] = array(
    'menu_name' => 'primary-links',
    'link_path' => 'node/1560',
    'router_path' => 'node/%',
    'link_title' => 'Electronic Security',
    'options' => array(
      'attributes' => array(),
    ),
    'module' => 'menu',
    'hidden' => '0',
    'external' => '0',
    'has_children' => '0',
    'expanded' => '0',
    'weight' => '-49',
    'parent_path' => 'node/1574',
  );
  // Exported menu link: primary-links:node/1561
  $menu_links['primary-links:node/1561'] = array(
    'menu_name' => 'primary-links',
    'link_path' => 'node/1561',
    'router_path' => 'node/%',
    'link_title' => 'Integrated Data Networks',
    'options' => array(
      'attributes' => array(),
    ),
    'module' => 'menu',
    'hidden' => '0',
    'external' => '0',
    'has_children' => '0',
    'expanded' => '0',
    'weight' => '-48',
    'parent_path' => 'node/1574',
  );
  // Exported menu link: primary-links:node/1562
  $menu_links['primary-links:node/1562'] = array(
    'menu_name' => 'primary-links',
    'link_path' => 'node/1562',
    'router_path' => 'node/%',
    'link_title' => 'Building Information Modeling (BIM)',
    'options' => array(
      'attributes' => array(),
    ),
    'module' => 'menu',
    'hidden' => '0',
    'external' => '0',
    'has_children' => '0',
    'expanded' => '0',
    'weight' => '-50',
    'parent_path' => 'node/1573',
  );
  // Exported menu link: primary-links:node/1563
  $menu_links['primary-links:node/1563'] = array(
    'menu_name' => 'primary-links',
    'link_path' => 'node/1563',
    'router_path' => 'node/%',
    'link_title' => 'Fire Protection',
    'options' => array(
      'attributes' => array(),
    ),
    'module' => 'menu',
    'hidden' => '0',
    'external' => '0',
    'has_children' => '0',
    'expanded' => '0',
    'weight' => '-49',
    'parent_path' => 'node/1573',
  );
  // Exported menu link: primary-links:node/1565
  $menu_links['primary-links:node/1565'] = array(
    'menu_name' => 'primary-links',
    'link_path' => 'node/1565',
    'router_path' => 'node/%',
    'link_title' => 'Master Planning',
    'options' => array(
      'attributes' => array(),
    ),
    'module' => 'menu',
    'hidden' => '0',
    'external' => '0',
    'has_children' => '0',
    'expanded' => '0',
    'weight' => '-45',
    'parent_path' => 'node/1573',
  );
  // Exported menu link: primary-links:node/1566
  $menu_links['primary-links:node/1566'] = array(
    'menu_name' => 'primary-links',
    'link_path' => 'node/1566',
    'router_path' => 'node/%',
    'link_title' => 'Program Management',
    'options' => array(
      'attributes' => array(),
    ),
    'module' => 'menu',
    'hidden' => '0',
    'external' => '0',
    'has_children' => '0',
    'expanded' => '0',
    'weight' => '-44',
    'parent_path' => 'node/1573',
  );
  // Exported menu link: primary-links:node/1567
  $menu_links['primary-links:node/1567'] = array(
    'menu_name' => 'primary-links',
    'link_path' => 'node/1567',
    'router_path' => 'node/%',
    'link_title' => 'Site Planning and Selection',
    'options' => array(
      'attributes' => array(),
    ),
    'module' => 'menu',
    'hidden' => '0',
    'external' => '0',
    'has_children' => '0',
    'expanded' => '0',
    'weight' => '-43',
    'parent_path' => 'node/1573',
  );
  // Exported menu link: primary-links:node/1568
  $menu_links['primary-links:node/1568'] = array(
    'menu_name' => 'primary-links',
    'link_path' => 'node/1568',
    'router_path' => 'node/%',
    'link_title' => 'Sustainable/Green Design',
    'options' => array(
      'attributes' => array(),
    ),
    'module' => 'menu',
    'hidden' => '0',
    'external' => '0',
    'has_children' => '0',
    'expanded' => '0',
    'weight' => '-42',
    'parent_path' => 'node/1573',
  );
  // Exported menu link: primary-links:node/1569
  $menu_links['primary-links:node/1569'] = array(
    'menu_name' => 'primary-links',
    'link_path' => 'node/1569',
    'router_path' => 'node/%',
    'link_title' => 'Capital Planning and Strategy',
    'options' => array(
      'attributes' => array(),
    ),
    'module' => 'menu',
    'hidden' => '0',
    'external' => '0',
    'has_children' => '0',
    'expanded' => '0',
    'weight' => '-50',
    'parent_path' => 'node/1572',
  );
  // Exported menu link: primary-links:node/1570
  $menu_links['primary-links:node/1570'] = array(
    'menu_name' => 'primary-links',
    'link_path' => 'node/1570',
    'router_path' => 'node/%',
    'link_title' => 'Due Diligence and Independent Engineering',
    'options' => array(
      'attributes' => array(),
    ),
    'module' => 'menu',
    'hidden' => '0',
    'external' => '0',
    'has_children' => '0',
    'expanded' => '0',
    'weight' => '-49',
    'parent_path' => 'node/1572',
  );
  // Exported menu link: primary-links:node/1571
  $menu_links['primary-links:node/1571'] = array(
    'menu_name' => 'primary-links',
    'link_path' => 'node/1571',
    'router_path' => 'node/%',
    'link_title' => 'Energy and Fuel Market Consulting',
    'options' => array(
      'attributes' => array(),
    ),
    'module' => 'menu',
    'hidden' => '0',
    'external' => '0',
    'has_children' => '0',
    'expanded' => '0',
    'weight' => '-48',
    'parent_path' => 'node/1572',
  );
  // Exported menu link: primary-links:node/1572
  $menu_links['primary-links:node/1572'] = array(
    'menu_name' => 'primary-links',
    'link_path' => 'node/1572',
    'router_path' => 'node/%',
    'link_title' => 'Business and Financial Advisory',
    'options' => array(
      'attributes' => array(),
    ),
    'module' => 'menu',
    'hidden' => '0',
    'external' => '0',
    'has_children' => '1',
    'expanded' => '1',
    'weight' => '-48',
    'parent_path' => 'node/1558',
  );
  // Exported menu link: primary-links:node/1573
  $menu_links['primary-links:node/1573'] = array(
    'menu_name' => 'primary-links',
    'link_path' => 'node/1573',
    'router_path' => 'node/%',
    'link_title' => 'Architecture',
    'options' => array(
      'attributes' => array(),
    ),
    'module' => 'menu',
    'hidden' => '0',
    'external' => '0',
    'has_children' => '1',
    'expanded' => '1',
    'weight' => '-49',
    'parent_path' => 'node/1558',
  );
  // Exported menu link: primary-links:node/1574
  $menu_links['primary-links:node/1574'] = array(
    'menu_name' => 'primary-links',
    'link_path' => 'node/1574',
    'router_path' => 'node/%',
    'link_title' => 'Advanced Communication Systems',
    'options' => array(
      'attributes' => array(),
    ),
    'module' => 'menu',
    'hidden' => '0',
    'external' => '0',
    'has_children' => '1',
    'expanded' => '1',
    'weight' => '-50',
    'parent_path' => 'node/1558',
  );
  // Exported menu link: primary-links:node/1575
  $menu_links['primary-links:node/1575'] = array(
    'menu_name' => 'primary-links',
    'link_path' => 'node/1575',
    'router_path' => 'node/%',
    'link_title' => 'Integrated Resource Planning',
    'options' => array(
      'attributes' => array(),
    ),
    'module' => 'menu',
    'hidden' => '0',
    'external' => '0',
    'has_children' => '0',
    'expanded' => '0',
    'weight' => '-47',
    'parent_path' => 'node/1572',
  );
  // Exported menu link: primary-links:node/1576
  $menu_links['primary-links:node/1576'] = array(
    'menu_name' => 'primary-links',
    'link_path' => 'node/1576',
    'router_path' => 'node/%',
    'link_title' => 'Program Management / Owner\'s Advisory',
    'options' => array(
      'attributes' => array(),
    ),
    'module' => 'menu',
    'hidden' => '0',
    'external' => '0',
    'has_children' => '0',
    'expanded' => '0',
    'weight' => '-46',
    'parent_path' => 'node/1572',
  );
  // Exported menu link: primary-links:node/1577
  $menu_links['primary-links:node/1577'] = array(
    'menu_name' => 'primary-links',
    'link_path' => 'node/1577',
    'router_path' => 'node/%',
    'link_title' => 'Rates and Regulatory Consulting',
    'options' => array(
      'attributes' => array(),
    ),
    'module' => 'menu',
    'hidden' => '0',
    'external' => '0',
    'has_children' => '0',
    'expanded' => '0',
    'weight' => '-45',
    'parent_path' => 'node/1572',
  );
  // Exported menu link: primary-links:node/1578
  $menu_links['primary-links:node/1578'] = array(
    'menu_name' => 'primary-links',
    'link_path' => 'node/1578',
    'router_path' => 'node/%',
    'link_title' => 'Valuations and Appraisals',
    'options' => array(
      'attributes' => array(),
    ),
    'module' => 'menu',
    'hidden' => '0',
    'external' => '0',
    'has_children' => '0',
    'expanded' => '0',
    'weight' => '-44',
    'parent_path' => 'node/1572',
  );
  // Exported menu link: primary-links:node/1579
  $menu_links['primary-links:node/1579'] = array(
    'menu_name' => 'primary-links',
    'link_path' => 'node/1579',
    'router_path' => 'node/%',
    'link_title' => 'Commissioning and Start-Up',
    'options' => array(
      'attributes' => array(),
    ),
    'module' => 'menu',
    'hidden' => '0',
    'external' => '0',
    'has_children' => '0',
    'expanded' => '0',
    'weight' => '-50',
    'parent_path' => 'node/1581',
  );
  // Exported menu link: primary-links:node/1580
  $menu_links['primary-links:node/1580'] = array(
    'menu_name' => 'primary-links',
    'link_path' => 'node/1580',
    'router_path' => 'node/%',
    'link_title' => 'Construction',
    'options' => array(
      'attributes' => array(),
    ),
    'module' => 'menu',
    'hidden' => '0',
    'external' => '0',
    'has_children' => '0',
    'expanded' => '0',
    'weight' => '-49',
    'parent_path' => 'node/1581',
  );
  // Exported menu link: primary-links:node/1581
  $menu_links['primary-links:node/1581'] = array(
    'menu_name' => 'primary-links',
    'link_path' => 'node/1581',
    'router_path' => 'node/%',
    'link_title' => 'DesignBuild Project Delivery',
    'options' => array(
      'attributes' => array(),
    ),
    'module' => 'menu',
    'hidden' => '0',
    'external' => '0',
    'has_children' => '1',
    'expanded' => '1',
    'weight' => '-47',
    'parent_path' => 'node/1558',
  );
  // Exported menu link: primary-links:node/1582
  $menu_links['primary-links:node/1582'] = array(
    'menu_name' => 'primary-links',
    'link_path' => 'node/1582',
    'router_path' => 'node/%',
    'link_title' => 'Pre-construction',
    'options' => array(
      'attributes' => array(),
    ),
    'module' => 'menu',
    'hidden' => '0',
    'external' => '0',
    'has_children' => '0',
    'expanded' => '0',
    'weight' => '-48',
    'parent_path' => 'node/1581',
  );
  // Exported menu link: primary-links:node/262
  $menu_links['primary-links:node/262'] = array(
    'menu_name' => 'primary-links',
    'link_path' => 'node/262',
    'router_path' => 'node/%',
    'link_title' => 'Home',
    'options' => array(
      'attributes' => array(),
    ),
    'module' => 'menu',
    'hidden' => '0',
    'external' => '0',
    'has_children' => '1',
    'expanded' => '0',
    'weight' => '-50',
    'parent_path' => 'http://www.saic.com/engineering',
  );
  // Exported menu link: primary-links:node/2687
  $menu_links['primary-links:node/2687'] = array(
    'menu_name' => 'primary-links',
    'link_path' => 'node/2687',
    'router_path' => 'node/%',
    'link_title' => 'Integrated Network Solutions',
    'options' => array(
      'attributes' => array(),
    ),
    'module' => 'menu',
    'hidden' => '0',
    'external' => '0',
    'has_children' => '1',
    'expanded' => '1',
    'weight' => '-43',
    'parent_path' => 'node/1558',
  );
  // Exported menu link: primary-links:node/2688
  $menu_links['primary-links:node/2688'] = array(
    'menu_name' => 'primary-links',
    'link_path' => 'node/2688',
    'router_path' => 'node/%',
    'link_title' => 'Critical Infrastructure Communications',
    'options' => array(
      'attributes' => array(),
    ),
    'module' => 'menu',
    'hidden' => '0',
    'external' => '0',
    'has_children' => '0',
    'expanded' => '0',
    'weight' => '-50',
    'parent_path' => 'node/2687',
  );
  // Exported menu link: primary-links:node/2689
  $menu_links['primary-links:node/2689'] = array(
    'menu_name' => 'primary-links',
    'link_path' => 'node/2689',
    'router_path' => 'node/%',
    'link_title' => 'Critical Infrastructure Security',
    'options' => array(
      'attributes' => array(),
    ),
    'module' => 'menu',
    'hidden' => '0',
    'external' => '0',
    'has_children' => '1',
    'expanded' => '1',
    'weight' => '-49',
    'parent_path' => 'node/2687',
  );
  // Exported menu link: primary-links:node/2690
  $menu_links['primary-links:node/2690'] = array(
    'menu_name' => 'primary-links',
    'link_path' => 'node/2690',
    'router_path' => 'node/%',
    'link_title' => 'Enterprise Network Integration',
    'options' => array(
      'attributes' => array(),
    ),
    'module' => 'menu',
    'hidden' => '0',
    'external' => '0',
    'has_children' => '0',
    'expanded' => '0',
    'weight' => '-48',
    'parent_path' => 'node/2687',
  );
  // Exported menu link: primary-links:node/2691
  $menu_links['primary-links:node/2691'] = array(
    'menu_name' => 'primary-links',
    'link_path' => 'node/2691',
    'router_path' => 'node/%',
    'link_title' => 'Energy and Utility Industry Solutions',
    'options' => array(
      'attributes' => array(),
    ),
    'module' => 'menu',
    'hidden' => '0',
    'external' => '0',
    'has_children' => '1',
    'expanded' => '1',
    'weight' => '-47',
    'parent_path' => 'node/2687',
  );
  // Exported menu link: primary-links:node/2692
  $menu_links['primary-links:node/2692'] = array(
    'menu_name' => 'primary-links',
    'link_path' => 'node/2692',
    'router_path' => 'node/%',
    'link_title' => 'Managed Network Services',
    'options' => array(
      'attributes' => array(),
    ),
    'module' => 'menu',
    'hidden' => '0',
    'external' => '0',
    'has_children' => '1',
    'expanded' => '1',
    'weight' => '-46',
    'parent_path' => 'node/2687',
  );
  // Exported menu link: primary-links:node/2694
  $menu_links['primary-links:node/2694'] = array(
    'menu_name' => 'primary-links',
    'link_path' => 'node/2694',
    'router_path' => 'node/%',
    'link_title' => 'NERC Compliance',
    'options' => array(
      'attributes' => array(),
    ),
    'module' => 'menu',
    'hidden' => '0',
    'external' => '0',
    'has_children' => '0',
    'expanded' => '0',
    'weight' => '-49',
    'parent_path' => 'node/1611',
  );
  // Exported menu link: primary-links:node/2695
  $menu_links['primary-links:node/2695'] = array(
    'menu_name' => 'primary-links',
    'link_path' => 'node/2695',
    'router_path' => 'node/%',
    'link_title' => 'Satellite Comms for Today\'s Industries',
    'options' => array(
      'attributes' => array(),
    ),
    'module' => 'menu',
    'hidden' => '0',
    'external' => '0',
    'has_children' => '0',
    'expanded' => '0',
    'weight' => '-50',
    'parent_path' => 'node/2691',
  );
  // Exported menu link: primary-links:node/2696
  $menu_links['primary-links:node/2696'] = array(
    'menu_name' => 'primary-links',
    'link_path' => 'node/2696',
    'router_path' => 'node/%',
    'link_title' => 'Industrial Wireless',
    'options' => array(
      'attributes' => array(),
    ),
    'module' => 'menu',
    'hidden' => '0',
    'external' => '0',
    'has_children' => '0',
    'expanded' => '0',
    'weight' => '-49',
    'parent_path' => 'node/2691',
  );
  // Exported menu link: primary-links:node/2697
  $menu_links['primary-links:node/2697'] = array(
    'menu_name' => 'primary-links',
    'link_path' => 'node/2697',
    'router_path' => 'node/%',
    'link_title' => 'Security',
    'options' => array(
      'attributes' => array(),
    ),
    'module' => 'menu',
    'hidden' => '0',
    'external' => '0',
    'has_children' => '0',
    'expanded' => '0',
    'weight' => '-47',
    'parent_path' => 'node/2691',
  );
  // Exported menu link: primary-links:node/2698
  $menu_links['primary-links:node/2698'] = array(
    'menu_name' => 'primary-links',
    'link_path' => 'node/2698',
    'router_path' => 'node/%',
    'link_title' => 'Nuclear Cybersecurity',
    'options' => array(
      'attributes' => array(),
    ),
    'module' => 'menu',
    'hidden' => '0',
    'external' => '0',
    'has_children' => '0',
    'expanded' => '0',
    'weight' => '-50',
    'parent_path' => 'node/2689',
  );
  // Exported menu link: primary-links:node/2699
  $menu_links['primary-links:node/2699'] = array(
    'menu_name' => 'primary-links',
    'link_path' => 'node/2699',
    'router_path' => 'node/%',
    'link_title' => 'Smart Grid Security',
    'options' => array(
      'attributes' => array(),
    ),
    'module' => 'menu',
    'hidden' => '0',
    'external' => '0',
    'has_children' => '0',
    'expanded' => '0',
    'weight' => '-46',
    'parent_path' => 'node/2691',
  );
  // Exported menu link: primary-links:node/2700
  $menu_links['primary-links:node/2700'] = array(
    'menu_name' => 'primary-links',
    'link_path' => 'node/2700',
    'router_path' => 'node/%',
    'link_title' => 'Remote Access',
    'options' => array(
      'attributes' => array(),
    ),
    'module' => 'menu',
    'hidden' => '0',
    'external' => '0',
    'has_children' => '0',
    'expanded' => '0',
    'weight' => '-50',
    'parent_path' => 'node/2692',
  );
  // Exported menu link: primary-links:node/2701
  $menu_links['primary-links:node/2701'] = array(
    'menu_name' => 'primary-links',
    'link_path' => 'node/2701',
    'router_path' => 'node/%',
    'link_title' => 'LAN/WAN Service',
    'options' => array(
      'attributes' => array(),
    ),
    'module' => 'menu',
    'hidden' => '0',
    'external' => '0',
    'has_children' => '0',
    'expanded' => '0',
    'weight' => '-49',
    'parent_path' => 'node/2692',
  );
  // Exported menu link: primary-links:node/2702
  $menu_links['primary-links:node/2702'] = array(
    'menu_name' => 'primary-links',
    'link_path' => 'node/2702',
    'router_path' => 'node/%',
    'link_title' => 'IP Telephony and PBX Service',
    'options' => array(
      'attributes' => array(),
    ),
    'module' => 'menu',
    'hidden' => '0',
    'external' => '0',
    'has_children' => '0',
    'expanded' => '0',
    'weight' => '-48',
    'parent_path' => 'node/2692',
  );
  // Exported menu link: primary-links:node/2703
  $menu_links['primary-links:node/2703'] = array(
    'menu_name' => 'primary-links',
    'link_path' => 'node/2703',
    'router_path' => 'node/%',
    'link_title' => 'Application Servers',
    'options' => array(
      'attributes' => array(),
    ),
    'module' => 'menu',
    'hidden' => '0',
    'external' => '0',
    'has_children' => '0',
    'expanded' => '0',
    'weight' => '-47',
    'parent_path' => 'node/2692',
  );
  // Exported menu link: primary-links:node/2704
  $menu_links['primary-links:node/2704'] = array(
    'menu_name' => 'primary-links',
    'link_path' => 'node/2704',
    'router_path' => 'node/%',
    'link_title' => 'Telecom Expense Management',
    'options' => array(
      'attributes' => array(),
    ),
    'module' => 'menu',
    'hidden' => '0',
    'external' => '0',
    'has_children' => '0',
    'expanded' => '0',
    'weight' => '-46',
    'parent_path' => 'node/2692',
  );
  // Exported menu link: primary-links:node/2705
  $menu_links['primary-links:node/2705'] = array(
    'menu_name' => 'primary-links',
    'link_path' => 'node/2705',
    'router_path' => 'node/%',
    'link_title' => 'Passive Optical Networking',
    'options' => array(
      'attributes' => array(),
    ),
    'module' => 'menu',
    'hidden' => '0',
    'external' => '0',
    'has_children' => '0',
    'expanded' => '0',
    'weight' => '-44',
  );
  // Exported menu link: primary-links:node/2708
  $menu_links['primary-links:node/2708'] = array(
    'menu_name' => 'primary-links',
    'link_path' => 'node/2708',
    'router_path' => 'node/%',
    'link_title' => 'Nuclear Plant Wireless Communications',
    'options' => array(
      'attributes' => array(),
    ),
    'module' => 'menu',
    'hidden' => '0',
    'external' => '0',
    'has_children' => '0',
    'expanded' => '0',
    'weight' => '-48',
    'parent_path' => 'node/2691',
  );
  // Exported menu link: primary-links:node/2709
  $menu_links['primary-links:node/2709'] = array(
    'menu_name' => 'primary-links',
    'link_path' => 'node/2709',
    'router_path' => 'node/%',
    'link_title' => 'Network Consulting',
    'options' => array(
      'attributes' => array(),
    ),
    'module' => 'menu',
    'hidden' => '0',
    'external' => '0',
    'has_children' => '0',
    'expanded' => '0',
    'weight' => '-45',
    'parent_path' => 'node/2687',
  );
  // Exported menu link: primary-links:node/2822
  $menu_links['primary-links:node/2822'] = array(
    'menu_name' => 'primary-links',
    'link_path' => 'node/2822',
    'router_path' => 'node/%',
    'link_title' => 'Transportation',
    'options' => array(
      'attributes' => array(),
    ),
    'module' => 'menu',
    'hidden' => '0',
    'external' => '0',
    'has_children' => '1',
    'expanded' => '1',
    'weight' => '-40',
    'parent_path' => 'node/1558',
  );
  // Exported menu link: primary-links:node/2823
  $menu_links['primary-links:node/2823'] = array(
    'menu_name' => 'primary-links',
    'link_path' => 'node/2823',
    'router_path' => 'node/%',
    'link_title' => 'Aviation Management',
    'options' => array(
      'attributes' => array(),
    ),
    'module' => 'menu',
    'hidden' => '0',
    'external' => '0',
    'has_children' => '1',
    'expanded' => '1',
    'weight' => '-50',
    'parent_path' => 'node/2822',
  );
  // Exported menu link: primary-links:node/2824
  $menu_links['primary-links:node/2824'] = array(
    'menu_name' => 'primary-links',
    'link_path' => 'node/2824',
    'router_path' => 'node/%',
    'link_title' => 'Airside and Landside Operations',
    'options' => array(
      'attributes' => array(),
    ),
    'module' => 'menu',
    'hidden' => '0',
    'external' => '0',
    'has_children' => '0',
    'expanded' => '0',
    'weight' => '-50',
    'parent_path' => 'node/2823',
  );
  // Exported menu link: primary-links:node/2825
  $menu_links['primary-links:node/2825'] = array(
    'menu_name' => 'primary-links',
    'link_path' => 'node/2825',
    'router_path' => 'node/%',
    'link_title' => 'Aviation Information Technology',
    'options' => array(
      'attributes' => array(),
    ),
    'module' => 'menu',
    'hidden' => '0',
    'external' => '0',
    'has_children' => '0',
    'expanded' => '0',
    'weight' => '-49',
    'parent_path' => 'node/2823',
  );
  // Exported menu link: primary-links:node/2826
  $menu_links['primary-links:node/2826'] = array(
    'menu_name' => 'primary-links',
    'link_path' => 'node/2826',
    'router_path' => 'node/%',
    'link_title' => 'Airport Security',
    'options' => array(
      'attributes' => array(),
    ),
    'module' => 'menu',
    'hidden' => '0',
    'external' => '0',
    'has_children' => '0',
    'expanded' => '0',
    'weight' => '-48',
    'parent_path' => 'node/2823',
  );
  // Exported menu link: primary-links:node/2829
  $menu_links['primary-links:node/2829'] = array(
    'menu_name' => 'primary-links',
    'link_path' => 'node/2829',
    'router_path' => 'node/%',
    'link_title' => 'Transportation Safety and Security',
    'options' => array(
      'attributes' => array(),
    ),
    'module' => 'menu',
    'hidden' => '0',
    'external' => '0',
    'has_children' => '0',
    'expanded' => '0',
    'weight' => '-42',
    'parent_path' => 'node/2822',
  );
  // Exported menu link: primary-links:node/3091
  $menu_links['primary-links:node/3091'] = array(
    'menu_name' => 'primary-links',
    'link_path' => 'node/3091',
    'router_path' => 'node/%',
    'link_title' => 'Systems Engineering',
    'options' => array(
      'attributes' => array(),
    ),
    'module' => 'menu',
    'hidden' => '0',
    'external' => '0',
    'has_children' => '1',
    'expanded' => '1',
    'weight' => '0',
    'parent_path' => 'node/9607',
  );
  // Exported menu link: primary-links:node/3092
  $menu_links['primary-links:node/3092'] = array(
    'menu_name' => 'primary-links',
    'link_path' => 'node/3092',
    'router_path' => 'node/%',
    'link_title' => 'Integration Approach',
    'options' => array(
      'attributes' => array(
        'title' => 'Systems Engineering and Integration Approach',
      ),
    ),
    'module' => 'menu',
    'hidden' => '0',
    'external' => '0',
    'has_children' => '0',
    'expanded' => '0',
    'weight' => '0',
    'parent_path' => 'node/3091',
  );
  // Exported menu link: primary-links:node/310
  $menu_links['primary-links:node/310'] = array(
    'menu_name' => 'primary-links',
    'link_path' => 'node/310',
    'router_path' => 'node/%',
    'link_title' => 'Who We Serve',
    'options' => array(
      'attributes' => array(),
    ),
    'module' => 'menu',
    'hidden' => '0',
    'external' => '0',
    'has_children' => '1',
    'expanded' => '0',
    'weight' => '-49',
    'parent_path' => 'http://www.saic.com/engineering',
  );
  // Exported menu link: primary-links:node/311
  $menu_links['primary-links:node/311'] = array(
    'menu_name' => 'primary-links',
    'link_path' => 'node/311',
    'router_path' => 'node/%',
    'link_title' => 'Capabilities',
    'options' => array(
      'attributes' => array(),
    ),
    'module' => 'menu',
    'hidden' => '0',
    'external' => '0',
    'has_children' => '1',
    'expanded' => '0',
    'weight' => '-48',
    'parent_path' => 'http://www.saic.com/engineering',
  );
  // Exported menu link: primary-links:node/312
  $menu_links['primary-links:node/312'] = array(
    'menu_name' => 'primary-links',
    'link_path' => 'node/312',
    'router_path' => 'node/%',
    'link_title' => 'Projects',
    'options' => array(
      'attributes' => array(),
    ),
    'module' => 'menu',
    'hidden' => '0',
    'external' => '0',
    'has_children' => '1',
    'expanded' => '0',
    'weight' => '-47',
    'parent_path' => 'http://www.saic.com/engineering',
  );
  // Exported menu link: primary-links:node/313
  $menu_links['primary-links:node/313'] = array(
    'menu_name' => 'primary-links',
    'link_path' => 'node/313',
    'router_path' => 'node/%',
    'link_title' => 'Newsroom',
    'options' => array(
      'attributes' => array(),
    ),
    'module' => 'menu',
    'hidden' => '0',
    'external' => '0',
    'has_children' => '1',
    'expanded' => '1',
    'weight' => '-46',
    'parent_path' => 'http://www.saic.com/engineering',
  );
  // Exported menu link: primary-links:node/3146
  $menu_links['primary-links:node/3146'] = array(
    'menu_name' => 'primary-links',
    'link_path' => 'node/3146',
    'router_path' => 'node/%',
    'link_title' => 'Emergency Management',
    'options' => array(
      'attributes' => array(),
    ),
    'module' => 'menu',
    'hidden' => '0',
    'external' => '0',
    'has_children' => '1',
    'expanded' => '1',
    'weight' => '-46',
    'parent_path' => 'node/1558',
  );
  // Exported menu link: primary-links:node/3147
  $menu_links['primary-links:node/3147'] = array(
    'menu_name' => 'primary-links',
    'link_path' => 'node/3147',
    'router_path' => 'node/%',
    'link_title' => 'Hazard Mitigation',
    'options' => array(
      'attributes' => array(),
    ),
    'module' => 'menu',
    'hidden' => '0',
    'external' => '0',
    'has_children' => '0',
    'expanded' => '0',
    'weight' => '-50',
    'parent_path' => 'node/3146',
  );
  // Exported menu link: primary-links:node/3148
  $menu_links['primary-links:node/3148'] = array(
    'menu_name' => 'primary-links',
    'link_path' => 'node/3148',
    'router_path' => 'node/%',
    'link_title' => 'Disaster Preparedness',
    'options' => array(
      'attributes' => array(),
    ),
    'module' => 'menu',
    'hidden' => '0',
    'external' => '0',
    'has_children' => '0',
    'expanded' => '0',
    'weight' => '-49',
    'parent_path' => 'node/3146',
  );
  // Exported menu link: primary-links:node/3149
  $menu_links['primary-links:node/3149'] = array(
    'menu_name' => 'primary-links',
    'link_path' => 'node/3149',
    'router_path' => 'node/%',
    'link_title' => 'Disaster Response',
    'options' => array(
      'attributes' => array(),
    ),
    'module' => 'menu',
    'hidden' => '0',
    'external' => '0',
    'has_children' => '0',
    'expanded' => '0',
    'weight' => '-48',
    'parent_path' => 'node/3146',
  );
  // Exported menu link: primary-links:node/3150
  $menu_links['primary-links:node/3150'] = array(
    'menu_name' => 'primary-links',
    'link_path' => 'node/3150',
    'router_path' => 'node/%',
    'link_title' => 'Disaster Recovery',
    'options' => array(
      'attributes' => array(),
    ),
    'module' => 'menu',
    'hidden' => '0',
    'external' => '0',
    'has_children' => '0',
    'expanded' => '0',
    'weight' => '-47',
    'parent_path' => 'node/3146',
  );
  // Exported menu link: primary-links:node/3452
  $menu_links['primary-links:node/3452'] = array(
    'menu_name' => 'primary-links',
    'link_path' => 'node/3452',
    'router_path' => 'node/%',
    'link_title' => 'About',
    'options' => array(
      'attributes' => array(),
    ),
    'module' => 'menu',
    'hidden' => '0',
    'external' => '0',
    'has_children' => '0',
    'expanded' => '0',
    'weight' => '-50',
    'parent_path' => 'http://www.saic.com/isr',
  );
  // Exported menu link: primary-links:node/3671
  $menu_links['primary-links:node/3671'] = array(
    'menu_name' => 'primary-links',
    'link_path' => 'node/3671',
    'router_path' => 'node/%',
    'link_title' => 'Who We Serve',
    'options' => array(
      'attributes' => array(),
    ),
    'module' => 'menu',
    'hidden' => '0',
    'external' => '0',
    'has_children' => '0',
    'expanded' => '0',
    'weight' => '-49',
    'parent_path' => 'http://www.saic.com/isr',
  );
  // Exported menu link: primary-links:node/3672
  $menu_links['primary-links:node/3672'] = array(
    'menu_name' => 'primary-links',
    'link_path' => 'node/3672',
    'router_path' => 'node/%',
    'link_title' => 'Capabilities',
    'options' => array(
      'attributes' => array(),
    ),
    'module' => 'menu',
    'hidden' => '0',
    'external' => '0',
    'has_children' => '1',
    'expanded' => '0',
    'weight' => '-48',
    'parent_path' => 'http://www.saic.com/isr',
  );
  // Exported menu link: primary-links:node/3673
  $menu_links['primary-links:node/3673'] = array(
    'menu_name' => 'primary-links',
    'link_path' => 'node/3673',
    'router_path' => 'node/%',
    'link_title' => 'Solutions',
    'options' => array(
      'attributes' => array(),
    ),
    'module' => 'menu',
    'hidden' => '0',
    'external' => '0',
    'has_children' => '0',
    'expanded' => '0',
    'weight' => '-47',
    'parent_path' => 'http://www.saic.com/isr',
  );
  // Exported menu link: primary-links:node/3674
  $menu_links['primary-links:node/3674'] = array(
    'menu_name' => 'primary-links',
    'link_path' => 'node/3674',
    'router_path' => 'node/%',
    'link_title' => 'Newsroom',
    'options' => array(
      'attributes' => array(),
    ),
    'module' => 'menu',
    'hidden' => '0',
    'external' => '0',
    'has_children' => '0',
    'expanded' => '0',
    'weight' => '-46',
    'parent_path' => 'http://www.saic.com/isr',
  );
  // Exported menu link: primary-links:node/369
  $menu_links['primary-links:node/369'] = array(
    'menu_name' => 'primary-links',
    'link_path' => 'node/369',
    'router_path' => 'node/%',
    'link_title' => 'Industry Rankings',
    'options' => array(
      'attributes' => array(),
    ),
    'module' => 'menu',
    'hidden' => '0',
    'external' => '0',
    'has_children' => '0',
    'expanded' => '0',
    'weight' => '-49',
    'parent_path' => 'node/313',
  );
  // Exported menu link: primary-links:node/4331
  $menu_links['primary-links:node/4331'] = array(
    'menu_name' => 'primary-links',
    'link_path' => 'node/4331',
    'router_path' => 'node/%',
    'link_title' => 'Intelligent Transportation Systems',
    'options' => array(
      'attributes' => array(),
    ),
    'module' => 'menu',
    'hidden' => '0',
    'external' => '0',
    'has_children' => '0',
    'expanded' => '0',
    'weight' => '-48',
    'parent_path' => 'node/2822',
  );
  // Exported menu link: primary-links:node/5630
  $menu_links['primary-links:node/5630'] = array(
    'menu_name' => 'primary-links',
    'link_path' => 'node/5630',
    'router_path' => 'node/%',
    'link_title' => 'Interior Design',
    'options' => array(
      'attributes' => array(),
    ),
    'module' => 'menu',
    'hidden' => '0',
    'external' => '0',
    'has_children' => '0',
    'expanded' => '0',
    'weight' => '-47',
    'parent_path' => 'node/1573',
  );
  // Exported menu link: primary-links:node/5631
  $menu_links['primary-links:node/5631'] = array(
    'menu_name' => 'primary-links',
    'link_path' => 'node/5631',
    'router_path' => 'node/%',
    'link_title' => 'Landscape Architecture',
    'options' => array(
      'attributes' => array(),
    ),
    'module' => 'menu',
    'hidden' => '0',
    'external' => '0',
    'has_children' => '0',
    'expanded' => '0',
    'weight' => '-46',
    'parent_path' => 'node/1573',
  );
  // Exported menu link: primary-links:node/632
  $menu_links['primary-links:node/632'] = array(
    'menu_name' => 'primary-links',
    'link_path' => 'node/632',
    'router_path' => 'node/%',
    'link_title' => 'Articles and Publications',
    'options' => array(
      'attributes' => array(),
    ),
    'module' => 'menu',
    'hidden' => '0',
    'external' => '0',
    'has_children' => '0',
    'expanded' => '0',
    'weight' => '-50',
    'parent_path' => 'node/313',
  );
  // Translatables
  // Included for use with string extractors like potx.
  t('About');
  t('Advanced Communication Systems');
  t('Airport Security');
  t('Airside and Landside Operations');
  t('Application Servers');
  t('Architecture');
  t('Articles and Publications');
  t('Audio/Video, Visualization and Wireless');
  t('Aviation Information Technology');
  t('Aviation Management');
  t('Building Information Modeling (BIM)');
  t('Business and Financial Advisory');
  t('Capabilities');
  t('Capital Planning and Strategy');
  t('Commissioning and Start-Up');
  t('Construction');
  t('Critical Infrastructure Communications');
  t('Critical Infrastructure Security');
  t('DesignBuild Project Delivery');
  t('Disaster Preparedness');
  t('Disaster Recovery');
  t('Disaster Response');
  t('Due Diligence and Independent Engineering');
  t('Electronic Security');
  t('Emergency Management');
  t('Energy and Fuel Market Consulting');
  t('Energy and Utility Industry Solutions');
  t('Enterprise Network Integration');
  t('Fire Protection');
  t('Food Protection Solutions');
  t('Hazard Mitigation');
  t('Home');
  t('IP Telephony and PBX Service');
  t('Industrial Wireless');
  t('Industry Rankings');
  t('Infrastructure');
  t('Integrated Data Networks');
  t('Integrated Network Solutions');
  t('Integrated Resource Planning');
  t('Integration Approach');
  t('Intelligent Transportation Systems');
  t('Interior Design');
  t('LAN/WAN Service');
  t('Landscape Architecture');
  t('Managed Network Services');
  t('Master Planning');
  t('NERC Compliance');
  t('Network Consulting');
  t('Newsroom');
  t('Nuclear Cybersecurity');
  t('Nuclear Plant Wireless Communications');
  t('Passive Optical Networking');
  t('Pre-construction');
  t('Program Management');
  t('Program Management / Owner\'s Advisory');
  t('Projects');
  t('Rates and Regulatory Consulting');
  t('Remote Access');
  t('Satellite Comms for Today\'s Industries');
  t('Security');
  t('Site Planning and Selection');
  t('Smart Grid Security');
  t('Solutions');
  t('Sustainable/Green Design');
  t('Systems Engineering');
  t('Telecom Expense Management');
  t('Transportation');
  t('Transportation Safety and Security');
  t('Valuations and Appraisals');
  t('Who We Serve');


  return $menu_links;
}
