<?php

/**
* Implementation of hook_context_default_contexts().
* 
*/
function saic_news_archive_contexts() {
  $contexts = digitaria_utility_install_context_dir('saic_news_archive');
  return $contexts;
}

/**
 * Implementation of hook_block().
 */
function saic_news_archive_block($op = 'list', $delta = 0, $edit = array()) {
  if ($op == 'list') {
    $blocks['news_arch_listing'] = array(
      'info' => t('News Listing'),
    );
    $blocks['news_arch_nav'] = array(
      'info' => t('Archive news nav'),
    );
    $blocks['news_arch_nav_left'] = array(
      'info' => t('Archive news nav left'),
    );
    $blocks['news_arch_top'] = array(
      'info' => t('Archive news top block'),
    );
    $blocks['news_arch_block_right'] = array(
      'info' => t('Archive news right block'),
    );

    return $blocks;
  }
  elseif ($op == 'view') {
    if ($delta == 'news_arch_listing') {
      $block =  saic_news_listing();
    }
    elseif ($delta == 'news_arch_nav') {
      $block =  saic_news_archive_year_nav();
    }
    elseif ($delta == 'news_arch_nav_left') {
      $block =  saic_news_archive_year_nav_left();
    }
    elseif ($delta == 'news_arch_top') {
      $block =  saic_news_archive_top();
    }
    elseif ($delta == 'news_arch_block_right') {
      $block =  saic_news_archive_block_right();
    }
    return $block;
  }
}

function  saic_news_listing() {
  $block['content'] = views_embed_view('news_index', 'page_1');
  return $block;
}

function saic_news_archive_top() {
  $block['content'] = theme('news_block_top');
  return $block;
}

function saic_news_archive_year_nav_left() {
  $block['content'] = theme('news_nav_left');
  return $block;
}

function saic_news_archive_block_right() {
  $block['content'] = theme('news_block_right');
  return $block;
}

function saic_news_archive_views_query_alter(&$view, &$query) {
  if($view->name == 'news_index') {

    if($_GET['view'] == 'all' || !($_GET['year']['value']['date'])) {
      unset($view->query->where['date']);
    }
    foreach($query->where[0]['clauses'] as $key => $value) {
      if ($value == "(node.title) = ('%s')") {
       $title = mysql_real_escape_string ($_REQUEST['search_box']);
       $query->where[0]['clauses'][$key] =  
        "(node.title like '%%$title%' OR 
          node_revisions.body like '%%$title%' 
      )";  
      }
    }
  } 
}

function saic_news_archive_theme() {
  return array(
    'news_archive_nav' => array(
      'arguments' => array('years' => NULL),
      'template' => 'block-archive-nav',
    ),
    'news_nav_left' => array(
      'template' => 'block-archive-nav-left',
    ),
    'news_block_right' => array(
      'arguments' => array('news_block_right' => NULL),
      'template' => 'block-archive-block',
    ),
    'news_block_top' => array(
      'arguments' => array('news_block_right' => NULL),
      'template' => 'block-archive-top',
    ),
  );
}

function saic_news_archive_year_nav() {
  $query ="
   SELECT DATE_FORMAT(node_data_field_announcement_date.field_announcement_date_value, '%Y') as year
   FROM node node 
   LEFT JOIN content_type_announcement node_data_field_announcement_date ON node.vid = node_data_field_announcement_date.vid
   WHERE node.type in ('announcement')
  GROUP BY DATE_FORMAT(node_data_field_announcement_date.field_announcement_date_value, '%Y')";
  $result = db_query($query);
   $years = array();
   while ($row = db_fetch_array($result)) {
     $years[] = $row['year'];
   }
  $block['content'] = theme('news_archive_nav',$years);
  return $block;
}

function saic_news_archive_views_default_views() {
  return views_install_view_dir('saic_news_archive');
}
