<?php

/**
* Implementation of hook_context_default_contexts().
* 
*/
function saic_homepage_contexts() {
  $contexts = digitaria_utility_install_context_dir('saic_homepage');
  return $contexts;
}


/**
 * Implementation of hook_block
 */
function saic_homepage_block($op = 'list', $delta = 0, $edit = array()) {
  switch ($op) {
    case 'list':
      $blocks['saic_homepage_rotator'] = array(
        'info' => t("Homepage rotator"),
      );
      $blocks['saic_homepage_callouts'] = array(
        'info' => t("Homepage callouts"),
      );
      $blocks['saic_homepage_twitter'] = array(
        'info' => t("Homepage twitter"),
      );
      return $blocks;
      break;
    case 'view':
      switch ($delta) {
        case 'saic_homepage_rotator':
          $settings = saic_homepage_load_settings('rotator');
          $items = $settings['rotator'];
          $block['content'] = theme('homepage_rotator',$items);
        break;
        case 'saic_homepage_callouts':
          $settings = saic_homepage_load_settings('callout');
          $items = $settings['callout'];
          $block['content'] =  theme('homepage_callouts_block',$items);
        break;
        case 'saic_homepage_twitter':
          $items = saic_homepage_get_tweets();
          $block['content'] =  theme('homepage_twitter_block_items',$items);
        break;
      }
      return $block;
      break;
  }
}

function saic_homepage_theme() {
  return array(
      'homepage_settings_form' => array(
          'arguments' => array('form' => NULL),
      ),
      'saic_homepage' => array(
          'template' => 'page-homepage',
          'arguments' => array(),
      ),
      'homepage_rotator' => array(
          'template' => 'block-rotator',
          'arguments' => array('slides' => NULL),
      ),
      'homepage_callouts_block' => array(
          'template' => 'block-callouts',
          'arguments' => array('callouts' => NULL),
      ),
      'homepage_twitter_block_items' => array(
          'template' => 'block-twitter',
          'arguments' => array('tweets'=>NULL),
      ),
  );
}

/**
 * Implementation of hook_menu().
 */
function saic_homepage_menu() {
  $items = array();
  $items['admin/settings/homepage'] = array(
    'title' => 'Homepage Settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('homepage_settings_form'),
    'access arguments' => array('administer homepage'),    
    'type' => MENU_NORMAL_ITEM,
  );

  $items['saic_homepage'] = array(
    'title' => 'SAIC: From Science to Solutions®',
    'access arguments' => array('access content'),
    'page callback' => 'saic_homepage_homepage',
    'type' => MENU_NORMAL_ITEM
  );
  return $items;
}

function saic_homepage_perm() {
  return array('administer homepage');
}

function saic_homepage_homepage() {
  drupal_add_css('css/homepage.css');
  drupal_add_js('js/slides.jquery.js');
  drupal_add_js('js/slides_settings.js');
  return theme('saic_homepage');
}

/**
 * Settings form.
 */
function homepage_settings_form($form_state) {

  $form = array();
  $form['homepage_rotator']['#tree'] = TRUE;
  $form['homepage_callout']['#tree'] = TRUE;
  $form['#attributes'] = array('enctype' => "multipart/form-data"); 
  $settings = saic_homepage_load_settings();

  $rotators = array(1=>NULL,2=>NULL,3=>NULL,4=>NULL,5=>NULL);
  $callouts = array(1=>NULL,2=>NULL,3=>NULL);

  foreach($rotators as $key => $values) {
    $weight = (isset($settings['rotator'][$key]['weight']) ? $settings['rotator'][$key]['weight'] : $key);
    $form['homepage_rotator'][$weight] = array(
     'file_name' => array(
        '#value' => $settings['rotator'][$key]['file_name'],
      ),
      'file_name_saved' => array(
        '#type' => 'hidden',
        '#value' => $settings['rotator'][$key]['file_name'],
      ),
      'element_id' => array(
        '#type' => 'hidden',
        '#value' => $key,
      ),
      'image' => array(
        '#type' => 'file',
        '#name' => 'homepage_rotator_'.$key,
        '#title' => t('Attach new file'),
        '#size' => 40
      ),
      'exclude' => array(
        '#type' => 'checkbox',
        '#default_value' => $settings['rotator'][$key]['exclude'],
        '#title' => t('Hide this slide'),
      ),
      'url' => array(
        '#type' => 'textfield',
        '#title' => t('URL'),
        '#default_value' => $settings['rotator'][$key]['url'],
        '#size' => 60,
        '#maxlength' => 128,
      ),
      'weight' => array(
          '#type' => 'weight',
          '#delta' => 5,
          '#default_value' =>  $weight,
          '#attributes' => array('class' => 'weight'),
          ),
      );
  }

  foreach($callouts as $key => $values) {
    $form['homepage_callout'][$key] = array(
     'file_name' => array(
        '#value' => $settings['callout'][$key]['file_name'],
      ),
      'file_name_saved' => array(
        '#type' => 'hidden',
        '#value' => $settings['callout'][$key]['file_name'],
      ),
      'image' => array(
        '#type' => 'file',
        '#name' => 'homepage_callout_'.$key,
        '#title' => t('Attach new file'),
        '#size' => 40
      ),
      'exclude' => array(
        '#type' => 'checkbox',
        '#default_value' => $settings['callout'][$key]['exclude'],
        '#title' => t('Hide this slide'),
      ),
      'url' => array(
        '#type' => 'textfield',
        '#title' => t('URL'),
        '#default_value' => $settings['callout'][$key]['url'],
        '#size' => 60,
        '#maxlength' => 128,
      ),
     );
    }

  $form['submit']=array(
    '#type'=>'submit',
    '#value'=>t('Save changes'),
  );

  return $form;
}


function saic_homepage_get_tweets() {

  module_load_include('inc', 'digi_twitter', 'digi_twitter.theme');

  $limit =  20;
  $feed = 'SAICinc';

  // Get the node ID for the tweet_feed of SAICinc
  $get_feed_id = "
  SELECT       
      node.nid as nid
  FROM 
    node node,      
    content_type_twitter_feed tweet_feed
  WHERE        
    node.status <> 0   
  AND        
    node.type = 'twitter_feed'
  AND
    field_twitter_feed_alias_value = '%s'
  AND
    node.vid = tweet_feed.vid
  ";
  
  $result = db_query($get_feed_id, $feed);
  $feed_id= db_fetch_array($result);

  $get_tweets = "
    SELECT       
     node.nid
    FROM 
      node node,       
      content_type_tweet tweet
    WHERE        
      node.status <> 0  
    AND        
      node.type = 'tweet'
    AND
      field_tweet_source_nid  = '". $feed_id['nid'] ."'
    AND
       node.vid = tweet.vid 
    GROUP BY 
      node.vid
    ORDER BY
      field_tweet_published_date_value DESC
    LIMIT 
      0, ". $limit;

   $data = array();
   $result = db_query($get_tweets);
   while ($row = db_fetch_array($result)) {
    $node = node_load($row['nid']);
    $date = $node->field_tweet_published_date[0]['value'];
    $guid = $node->field_tweet_guid[0]['value'];
    $days = floor((time() - strtotime($date))/86400);
    $row['days_since'] =  date('F d Y', strtotime($date)); 

    $link =  $row['days_since'];
    $twitter_link = theme_digi_twitter_tweet_body_link($node->body);
    $row['body'] = $twitter_link['body'];
    $row['link'] = $twitter_link['link'];

    if( !preg_match('/\brt\s*@(\w+)/i', $row['body'], $match) && strpos($row['body'], '@') === FALSE ) {
       $retweet = FALSE;
    } 
    else {
      $retweet = TRUE;
    }

    //Strip retweets and tweets with no links
    if(!empty($row['link']) && !$retweet ) {
      $data[] = $row;
    }
  }
 
  $dataret = array_slice($data, 0, 6);

  if($_GET['test'] == 1) {
    print_r($dataret);
  }

  return $dataret;
}

function theme_homepage_settings_form($form) {

    // the variable that will hold our form HTML output
    $output = '';
    $callout_header = array(
        'File Name',
        'File',
        'Exclude',
        'Link',
        '',
        );

    // Make sure the header count matches the column count
    $header = array(
        'File Name',
        'File',
        'Exclude',
        'Link',
        'Weight',
        '',
        '',
        );

    ksort($form['homepage_rotator']);

    foreach($form['homepage_callout'] as $id => $row) {
        if (!intval($id))
            continue;
        $this_row = array();
        $this_row[] = drupal_render($row['file_name']);
        $this_row[] = drupal_render($row['image']);
        $this_row[] = drupal_render($row['exclude']);
        $this_row[] = drupal_render($row['url']);
        $this_row[] = drupal_render($row['file_name_saved']);
        $table_rows_callout[] = array('data' => $this_row);
    }
    foreach($form['homepage_rotator'] as $id => $row) {
        if (!intval($id))
            continue;
        $this_row = array();
        $this_row[] = drupal_render($row['file_name']);
        $this_row[] = drupal_render($row['image']);
        $this_row[] = drupal_render($row['exclude']);
        $this_row[] = drupal_render($row['url']);
        $this_row[] = drupal_render($row['weight']);
        $this_row[] = drupal_render($row['file_name_saved']);
        $this_row[] = drupal_render($row['element_id']);
        $table_rows[] = array('data' => $this_row, 'class'=>'draggable');
    }

    $table_id = 'homepage_rotator';
    // this function is what brings in the javascript to make our table drag-and-droppable
    drupal_add_tabledrag($table_id , 'order', 'sibling', 'weight');   

    // over-write the 'my_items' form element with the markup generated from our table
    $form['homepage_rotator'] = array(
        '#type' => 'markup',
        '#prefix'=>'<h2>Homepage Rotator settings</h2><br>',
        '#value' => theme('table', $header, $table_rows, array('id' => $table_id)),
        '#weight' => '1',
        );

    $form['homepage_callout'] = array(
        '#type' => 'markup',
        '#prefix'=>'<h2>Callout Settings</h2><br>',
        '#value' => theme('table', $callout_header, $table_rows_callout, array('id' => 'homepage_callout')),
        );

    $output = drupal_render($form);
    return $output;
}

function homepage_settings_form_submit($form, &$form_state) {
  $file_path = $_SERVER['DOCUMENT_ROOT'].'/'.conf_path().'/files/homepage/';
  $homepage_rotator = array();
  $homepage_callout = array();

  foreach($_FILES as $name => $data){
    if(substr ( $name, 0,16 ) == 'homepage_rotator' && $data['error'] == 0){
      $index = substr ( $name, 17,1 );
      $homepage_rotator[$index]['file_name'] = $data['name'];
      $res =  move_uploaded_file($data['tmp_name'], $file_path.$data['name']);
    }

    if(substr ( $name, 0,16 ) == 'homepage_callout'  && $data['error'] == 0){
      $index = substr ( $name, 17,1 );
      $homepage_callout[$index]['file_name'] = $data['name'];
      $res =  move_uploaded_file($data['tmp_name'], $file_path.$data['name']);
    }
  }

  foreach ($form_state['values']['homepage_rotator'] as $index => $data) {
   $index = $data['element_id'];

    if(!isset($homepage_rotator[$index]['file_name'])) {
      $homepage_rotator[$index]['file_name'] = $data['file_name_saved'];
    }
   $homepage_rotator[$index]['url'] = $data['url'];
   $homepage_rotator[$index]['weight'] = $data['weight'];
   $homepage_rotator[$index]['exclude'] = $data['exclude'];
  }

  foreach ($form_state['values']['homepage_callout'] as $index => $data) {
    if(!isset($homepage_callout[$index]['file_name'])) {
      $homepage_callout[$index]['file_name'] = $data['file_name_saved'];
    }

   $homepage_callout[$index]['url'] = $data['url'];
   $homepage_callout[$index]['exclude'] = $data['exclude'];
  }

  foreach($homepage_rotator as $index => $data) {
    $data = base64_encode(gzcompress(serialize($data))); 
    db_query("insert into {saic_homepage} values ('rotator', '". $data."', '". $index."', '". $data['weight']."') on duplicate key update data = '". $data."', weight = '". $weight."'");
  }

  foreach($homepage_callout as $index => $data) {
    $data = base64_encode(gzcompress(serialize($data)));
    db_query("insert into {saic_homepage} values ('callout', '". $data."','". $index."','') on duplicate key update data = '". $data."'");
  }
}

function saic_homepage_load_settings($type = 'both') {
  $settings = array();

  if($type == 'both') {
    $sql = "select * from saic_homepage order by weight desc";
    $file_path = '';
  }
  else {
    $sql = "select * from saic_homepage where type = '$type' order by weight desc";
    $file_path = conf_path().'/files/homepage/';
  }

  $query = db_query($sql);
  while($row = db_fetch_array($query)) {
    $data = unserialize(gzuncompress(base64_decode($row['data'])));
    if($row['type'] == 'rotator' && (($type != 'both' && $data['exclude'] == 0) || ($type == 'both'))) {
      $index = $row['element_id'];  
      $settings['rotator'][$index]['url'] = $data['url'];
      $settings['rotator'][$index]['weight'] = $data['weight'];
      $settings['rotator'][$index]['exclude'] = $data['exclude'];
      $settings['rotator'][$index]['file_name'] =   $file_path .$data['file_name'];
    }
    elseif($row['type'] == 'callout' && (($type != 'both' && $data['exclude'] == 0) || ($type == 'both'))) {
      $index = $row['element_id'];  
      $settings['callout'][$index]['url'] = $data['url'];
      $settings['callout'][$index]['exclude'] = $data['exclude'];
      $settings['callout'][$index]['file_name'] =   $file_path.$data['file_name'];
    }
  }
  return $settings;
}
